"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, Bot, Boxes, Camera, CheckCircle2, ChevronRight, CircleGauge, CloudOff, Compass, Fuel, Gauge, PackageCheck, RefreshCw, Route, ScanLine, ShieldCheck, Signature, Sparkles, Truck, Wifi } from "lucide-react";
import { useLocalization } from "@/components/i18n/localization-provider";
import { ExperienceSettingsPanel } from "@/components/settings/experience-settings-panel";
import { detectOperationalAnomalies, optimizeStops, predictDelay } from "../lib/optimizer";
import type { CollectionSession, CollectionState, MissionStatus, Tone } from "../lib/types";
import { ActionLink, Badge, inputClass, Metric, PageHeader, Panel } from "./collection-ui";

const statusTone: Record<MissionStatus, Tone> = { assigned: "info", accepted: "info", en_route: "success", at_stop: "warning", loading: "warning", in_transit: "success", unloading: "warning", completed: "success", incident: "danger" };
const moduleCopy: Record<string, { eyebrow: string; title: string; subtitle: string; metrics: [string,string,string][]; highlights: string[] }> = {
  assignment: { eyebrow: "Dispatch intelligent", title: "Affectation automatique", subtitle: "Classe les missions selon la proximité, la capacité, les heures de conduite et les habilitations.", metrics: [["Missions à affecter","4","2 urgentes"],["Score moyen","94%","compatibilité conducteur"],["Gain estimé","38 min","sur la journée"]], highlights: ["Capacité véhicule vérifiée", "Temps de conduite réglementaire respecté", "Priorités hub et aéroport intégrées"] },
  "route-optimization": { eyebrow: "Plan de tournée", title: "Optimisation des tournées", subtitle: "Réordonne les arrêts selon le trafic, les fenêtres de remise et les risques de retard.", metrics: [["Distance évitée","12,8 km","-18% aujourd’hui"],["Temps gagné","27 min","tournée active"],["CO₂ évité","3,1 kg","estimation"]], highlights: ["Parcelles avant Hub DSS", "Évitement Patte d’Oie", "Arrivée hub prévue à 18:42"] },
  quantities: { eyebrow: "Contrôle contradictoire", title: "Validation des quantités", subtitle: "Compare le manifeste, les scans, les lots physiques et la signature de chaque point de remise.", metrics: [["Attendus","42","colis"],["Scannés","39","93%"],["Écart","3","à identifier"]], highlights: ["Écart bloquant au Relais Parcelles", "Double comptage automatiquement exclu", "Clôture impossible sans justification"] },
  batches: { eyebrow: "Intégrité logistique", title: "Contrôle des lots", subtitle: "Valide scellés, poids, destination, nombre de colis et chaîne de garde avant mouvement.", metrics: [["Lots à bord","3","2 conformes"],["Poids contrôlé","286,4 kg","capteur vérifié"],["Scellés","3/3","traçables"]], highlights: ["LOT-DSS-PAR-0718 conforme", "LOT-DSS-MRS-0718 conforme", "LOT-DSS-BRU-0718 sous contrôle"] },
  photos: { eyebrow: "Preuves terrain", title: "Photos des colis", subtitle: "Capture horodatée, géolocalisée et rattachée au scan sans exposer les documents privés.", metrics: [["Photos du jour","28","chiffrées"],["À compléter","3","écart Parcelles"],["Qualité","96%","images nettes"]], highlights: ["Vue générale du lot", "Scellé lisible", "Anomalie cadrée avec référence"] },
  signatures: { eyebrow: "Chaîne de garde", title: "Signatures électroniques", subtitle: "Formalise chaque transfert de responsabilité avec identité, heure, position et quantités.", metrics: [["Signatures","5","aujourd’hui"],["En attente","1","Relais Parcelles"],["Intégrité","100%","empreintes valides"]], highlights: ["Aminata Cissé — Liberté 6", "Moussa Ba — Plateau", "Signature Hub requise à destination"] },
  history: { eyebrow: "Traçabilité complète", title: "Historique des mouvements", subtitle: "Journal immuable des missions, scans, positions, remises, incidents et synchronisations.", metrics: [["Événements","184","7 derniers jours"],["Missions","23","terminées"],["Conformité","99,4%","événements complets"]], highlights: ["Filtres par mission et véhicule", "Export signé pour audit", "Horodatage dans le fuseau choisi"] },
  incidents: { eyebrow: "Gestion terrain", title: "Incidents", subtitle: "Déclare, documente et escalade tout événement affectant le véhicule, le parcours ou la marchandise.", metrics: [["Ouverts","2","1 prioritaire"],["Délai moyen","11 min","prise en charge"],["Résolus","17","ce mois"]], highlights: ["Écart de quantité", "Ralentissement N1", "Scellé remplacé et documenté"] },
  anomalies: { eyebrow: "Contrôle de tournée", title: "Anomalies à traiter", subtitle: "Regroupe les colis oubliés, écarts de quantité, détours inhabituels et retards constatés.", metrics: [["Anomalies","3","à vérifier"],["Vérifiées","97%","sur la tournée"],["Bloquantes","1","action requise"]], highlights: ["3 colis non scannés", "Arrêt 6 minutes au-delà du plan", "Aucun détour non autorisé"] },
  notifications: { eyebrow: "Priorités", title: "Notifications", subtitle: "Alertes métier classées par urgence, mission et action attendue.", metrics: [["Non lues","2","action terrain"],["Critiques","1","quantité"],["Système","0","tout opérationnel"]], highlights: ["Écart au Relais Parcelles", "Itinéraire recalculé", "Maintenance dans 3 284 km"] },
  messages: { eyebrow: "Coordination sécurisée", title: "Messagerie opérationnelle", subtitle: "Échanges contextualisés avec dispatch, relais, hubs et support, sans canal personnel.", metrics: [["Conversations","4","actives"],["Non lus","1","Dispatch"],["Réponse médiane","2 min","aujourd’hui"]], highlights: ["Dispatch Dakar", "Hub DSS — Réception", "Support flotte"] },
  planning: { eyebrow: "Organisation", title: "Planning", subtitle: "Missions, pauses, inspections et maintenances dans le fuseau local du conducteur.", metrics: [["Missions","3","aujourd’hui"],["Conduite","4 h 12","planifiée"],["Pause","45 min","à 19:00"]], highlights: ["Relais → Hub DSS", "Hub DSS → Port", "Inspection véhicule demain 07:30"] },
  maintenance: { eyebrow: "Flotte préventive", title: "Maintenance véhicule", subtitle: "Entretien programmé selon kilométrage, usage, alertes télématiques et inspections chauffeur.", metrics: [["Prochaine révision","3 284 km","prévision 12 août"],["Alertes","1","AdBlue"],["Disponibilité","98,7%","30 jours"]], highlights: ["Contrôle niveau AdBlue", "Pneumatiques conformes", "Freinage vérifié"] },
  mileage: { eyebrow: "Télématique", title: "Kilométrage", subtitle: "Suit compteur, distances mission, trajets hors mission et cohérence GPS.", metrics: [["Compteur","84 216 km","vérifié"],["Aujourd’hui","73,4 km","3 missions"],["Ce mois","2 184 km","-4%"]], highlights: ["Aucun trajet non affecté", "Écart compteur/GPS 0,2%", "Saisie de fin de service requise"] },
  fuel: { eyebrow: "Efficacité flotte", title: "Consommation carburant", subtitle: "Analyse remplissages, consommation réelle, ralenti et éco-conduite.", metrics: [["Réservoir","68%","autonomie 510 km"],["Moyenne","10,8 L/100","-0,6 L"],["Éco-score","91/100","excellent"]], highlights: ["Ralenti limité à 7 minutes", "Dernier plein vérifié", "Aucune anomalie de volume"] },
  "driver-documents": { eyebrow: "Conformité chauffeur", title: "Documents chauffeur", subtitle: "Permis, habilitations, visite médicale et formations avec accès privé et dates d’expiration.", metrics: [["Valides","5/5","documents"],["Prochaine échéance","64 jours","visite médicale"],["Habilitations","3","fret, ADR niveau 1"]], highlights: ["Permis C valide", "Badge zone fret actif", "Formation sécurité à jour"] },
  "vehicle-documents": { eyebrow: "Conformité véhicule", title: "Documents véhicule", subtitle: "Carte grise, assurance, contrôle technique et autorisations de circulation sécurisés.", metrics: [["Valides","6/6","documents"],["Assurance","142 jours","restants"],["Contrôle technique","31 jours","restants"]], highlights: ["Carte grise vérifiée", "Assurance marchandises active", "Autorisation portuaire valide"] },
  offline: { eyebrow: "Continuité terrain", title: "Mode hors ligne", subtitle: "Scans, photos, signatures et événements restent disponibles sans réseau puis sont resynchronisés de manière idempotente.", metrics: [["Cache local","Prêt","données chiffrées"],["Actions en file","2","non bloquantes"],["Autonomie","8 h","cartes & missions"]], highlights: ["Aucune donnée sensible en clair", "Conflits détectés à la reprise", "Files limitées et rejouées dans l’ordre"] },
  sync: { eyebrow: "Continuité terrain", title: "Synchronisation", subtitle: "Retrouve les actions effectuées hors ligne et signale les écarts à vérifier.", metrics: [["État","À jour","connexion active"],["En attente","2","photos"],["Dernière mise à jour","3 min","avec succès"]], highlights: ["Reprise disponible", "Actions sans doublon", "Écarts de quantité signalés"] },
  support: { eyebrow: "Assistance", title: "Support", subtitle: "Accès prioritaire aux équipes opérations, flotte, sécurité et assistance technique.", metrics: [["Disponibilité","24/7","opérations"],["Réponse","< 3 min","priorité haute"],["Tickets ouverts","1","AdBlue"]], highlights: ["Urgence sécurité", "Assistance mission", "Support matériel de scan"] },
  profile: { eyebrow: "Identité professionnelle", title: "Profil chauffeur", subtitle: "Coordonnées professionnelles, habilitations, préférences internationales et statistiques de conduite.", metrics: [["Score qualité","98/100","30 jours"],["Missions","428","terminées"],["Ancienneté","3 ans","Yobalelma"]], highlights: ["Ibrahima Diagne", "Base Dakar — Hub DSS", "Français · Wolof · Anglais"] },
  settings: { eyebrow: "Configuration", title: "Paramètres", subtitle: "Préférences de navigation, langue, unités, confidentialité, notifications et appareils autorisés.", metrics: [["Appareil","Sécurisé","liaison active"],["Langues","9","prises en charge"],["Session","8 h","durée maximale"]], highlights: ["Mode sombre automatique", "Unités métriques", "Alertes vocales prioritaires"] },
};

export function CollectionRoutePage({ segments, session, state }: { segments?: string[]; session: CollectionSession; state: CollectionState }) {
  const key = segments?.[0] ?? "dashboard";
  if (key === "dashboard") return <Dashboard state={state} />;
  if (key === "missions") return <Missions state={state} missionId={segments?.[1]} />;
  if (key === "scanner" || key === "loading" || key === "unloading" || key === "inventory") return <ScanOperations mode={key} state={state} />;
  if (key === "map" || key === "navigation") return <MapExperience navigationMode={key === "navigation"} state={state} />;
  if (key === "vehicle") return <VehiclePage state={state} />;
  const copy = moduleCopy[key] ?? { eyebrow: "Collection App", title: "Module opérationnel", subtitle: "Retrouvez les missions et actions de transport qui vous sont attribuées.", metrics: [["État","Opérationnel","à jour"],["Missions","Synchronisées","prêtes"],["Suivi","Actif","actions enregistrées"]], highlights: ["Priorités à jour", "Traçabilité complète", "Continuité disponible"] };
  return <GenericModule moduleKey={key} copy={copy} session={session} state={state} />;
}

function Dashboard({ state }: { state: CollectionState }) {
  const active = state.missions.find((mission)=>mission.status !== "completed")!; const delay = predictDelay(active, 1.12);
  return <div className="grid gap-5"><PageHeader eyebrow="Transport interne · Dakar" title="Bonjour Ibrahima, prêt pour la route ?" subtitle="La tournée active est synchronisée. Un écart de quantité doit être résolu avant le départ vers le Hub DSS." actions={<><ActionLink href="/collection/navigation">Continuer la navigation</ActionLink><ActionLink href="/collection/scanner" secondary>Scanner un colis</ActionLink></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Mission active" value={active.code.split("-").slice(-2).join("-")} detail={`${active.progress}% terminé`} tone="success" /><Metric label="Colis à bord" value="26 / 42" detail="286,4 kg" /><Metric label="ETA Hub DSS" value="18:42" detail={`risque retard ${delay.risk}%`} tone="warning" /><Metric label="Écart actuel" value="3 colis" detail="Relais Parcelles" tone="danger" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><MissionCard mission={active} /><Panel title="Priorités de la tournée"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="h-5 w-5" /></span><div><p className="font-black">Itinéraire optimisé</p><p className="mt-1 text-sm text-muted-foreground">12,8 km évités et arrivée au hub prévue avant la fenêtre de 19:00.</p></div></div><div className="mt-4 grid gap-2">{["Contrôler les 3 colis manquants", "Photographier le lot avant scellé", "Confirmer la quantité avec l’agent relais"].map((task,index)=><div key={task} className="flex items-center gap-3 rounded-lg bg-muted p-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-black text-xs font-black text-white">{index+1}</span><span className="text-sm font-bold">{task}</span></div>)}</div></Panel></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Prochains arrêts"><Stops mission={active} /></Panel><Panel title="État véhicule"><VehicleSummary state={state} /></Panel></div>
  </div>;
}

function Missions({ state, missionId }: { state: CollectionState; missionId?: string }) {
  const selected = missionId ? state.missions.find((mission)=>mission.id===missionId || mission.code===missionId) : undefined;
  if (selected) return <div className="grid gap-5"><PageHeader eyebrow={selected.code} title={selected.title} subtitle={`${selected.distanceKm} km · ${selected.packageCount} colis · ${selected.weightKg} kg`} actions={<ActionLink href="/collection/navigation">Lancer la navigation</ActionLink>} /><MissionCard mission={selected} /><Panel title="Arrêts et chaîne de garde"><Stops mission={selected} /></Panel></div>;
  return <div className="grid gap-5"><PageHeader eyebrow="Planning opérationnel" title="Tableau des missions" subtitle="Toutes les missions relais, hubs, aéroports, ports et centres de distribution affectées à votre service." actions={<ActionLink href="/collection/route-optimization">Optimiser la tournée</ActionLink>} /><div className="grid gap-3 sm:grid-cols-3"><Metric label="Aujourd’hui" value="3" detail="missions planifiées" /><Metric label="En cours" value="1" detail="aucun retard critique" tone="success" /><Metric label="À préparer" value="1" detail="départ à 21:00" tone="info" /></div><div className="grid gap-4">{state.missions.map((mission)=><MissionCard key={mission.id} mission={mission} />)}</div></div>;
}

function MissionCard({ mission }: { mission: CollectionState["missions"][number] }) {
  return <Panel><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-black text-primary"><Route className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-black">{mission.title}</p><Badge tone={statusTone[mission.status]}>{mission.status}</Badge><Badge tone={mission.priority === "urgent" ? "danger" : mission.priority === "high" ? "warning" : "neutral"}>{mission.priority}</Badge></div><p className="mt-1 text-xs font-bold text-muted-foreground">{mission.code} · {mission.packageCount} colis · {mission.weightKg} kg · {mission.distanceKm} km</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${mission.progress}%`}} /></div></div><Link href={`/collection/missions/${mission.id}`} className="inline-flex items-center gap-1 text-sm font-black text-primary">Détails <ChevronRight className="h-4 w-4" /></Link></div></Panel>;
}

function Stops({ mission }: { mission: CollectionState["missions"][number] }) {
  const { formatDate } = useLocalization();
  return <div className="grid gap-2">{mission.stops.map((stop,index)=><div key={stop.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 rounded-lg border p-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-black ${stop.status === "completed" ? "bg-success text-white" : stop.status === "arrived" ? "bg-primary text-white" : "bg-muted"}`}>{stop.status === "completed" ? <CheckCircle2 className="h-4 w-4" /> : index+1}</span><div><p className="font-black">{stop.name}</p><p className="text-xs font-semibold text-muted-foreground">{stop.address} · {formatDate(stop.eta)}</p></div><span className="text-right text-xs font-black">{stop.scannedPackages}/{stop.expectedPackages}<br/><span className="font-semibold text-muted-foreground">colis</span></span></div>)}</div>;
}

function ScanOperations({ mode, state }: { mode: string; state: CollectionState }) {
  const [code,setCode] = useState(""); const [message,setMessage] = useState(""); const [pending,setPending] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const normalized=code.trim().toUpperCase(); if (!/^YBL-[A-Z]{2}-\d{4}-\d{4}$/u.test(normalized) && !/^LOT-[A-Z0-9-]+$/u.test(normalized)) { setMessage("Code non reconnu. Vérifiez le QR ou le code-barres."); return; } setPending(true); try { const response=await fetch("/api/collection/movements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingCode:normalized,action:mode==="unloading"?"unloaded":"loaded",idempotencyKey:`${mode}:${normalized}:${Date.now().toString(36)}`})}); const result=await response.json() as { error?: string; synchronized?: boolean }; if(!response.ok) throw new Error(result.error || "L’opération n’a pas pu être enregistrée."); if(!result.synchronized) throw new Error("Cette opération n’a pas été synchronisée. Réessayez avant de poursuivre."); setMessage(`${normalized} validé et synchronisé.`); setCode(""); } catch (error) { setMessage(error instanceof Error && error.message ? error.message : "Connexion indisponible. L’opération n’a pas été enregistrée ; réessayez."); } finally { setPending(false); } };
  const title = mode === "loading" ? "Chargement camion" : mode === "unloading" ? "Déchargement contrôlé" : mode === "inventory" ? "Inventaire à bord" : "Scan QR & code-barres";
  const subtitle = mode === "inventory" ? "État physique et numérique des colis présents dans le véhicule." : "Chaque scan vérifie mission, lot, destination, doublon et état de chaîne de garde.";
  return <div className="grid gap-5"><PageHeader eyebrow="Opération terrain" title={title} subtitle={subtitle} actions={<Badge tone={pending ? "warning" : "success"}>{pending ? "Enregistrement…" : "Prêt"}</Badge>} />
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Scanner"><div className="grid place-items-center rounded-xl border border-dashed bg-muted/40 p-8 text-center"><span className="grid h-20 w-20 place-items-center rounded-2xl bg-black text-primary"><ScanLine className="h-10 w-10" /></span><p className="mt-4 text-lg font-black">Saisie sécurisée</p><p className="mt-1 text-sm text-muted-foreground">Saisissez la référence imprimée sous le QR ou le code-barres.</p></div><form className="mt-4 grid gap-3" onSubmit={submit}><input aria-label="Code colis ou lot" className={inputClass} placeholder="YBL-SN-2607-0101" value={code} onChange={(event)=>setCode(event.target.value)} /><button disabled={pending} className="h-11 rounded-lg bg-primary font-black text-white disabled:opacity-60" type="submit">{pending ? "Enregistrement…" : "Valider la référence"}</button></form>{message ? <p role="status" className={`mt-3 rounded-lg p-3 text-sm font-bold ${message.includes("validé et synchronisé") ? "bg-success/10 text-success" : "bg-error/10 text-error"}`}>{message}</p> : null}</Panel>
      <Panel title={`${state.packages.filter((item)=>item.status==="loaded").length} colis chargés`}><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2">Tracking</th><th>Lot</th><th>Destination</th><th>Poids</th><th>État</th></tr></thead><tbody>{state.packages.map((item)=><tr key={item.id} className="border-t"><td className="p-2 font-black">{item.trackingCode}</td><td>{item.batchCode}</td><td>{item.destination}</td><td>{item.weightKg.toFixed(1)} kg</td><td><Badge tone={item.status === "anomaly" ? "danger" : item.status === "loaded" ? "success" : "neutral"}>{item.status}</Badge></td></tr>)}</tbody></table></div></Panel></div>
  </div>;
}

function MapExperience({ navigationMode, state }: { navigationMode: boolean; state: CollectionState }) {
  const mission=state.missions[0]; const optimized=optimizeStops(mission.stops); const delay=predictDelay(mission,1.12);
  return <div className="grid gap-5"><PageHeader eyebrow={navigationMode ? "Guidage actif" : "Position temps réel"} title={navigationMode ? "Prochain arrêt : Relais Parcelles" : "GPS & supervision de parcours"} subtitle={navigationMode ? "Arrivée dans 2 minutes. Entrée recommandée par l’avenue principale." : "Position signée, géofencing des arrêts et comparaison permanente avec l’itinéraire autorisé."} actions={<Badge tone="success"><span className="mr-2 h-2 w-2 rounded-full bg-success pulse-dot" />GPS · ±{state.gps.accuracyMeters} m</Badge>} />
    <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Panel className="min-h-[460px]"><div className="collection-grid relative min-h-[420px] overflow-hidden rounded-xl bg-[#ede8dc]"><div className="absolute inset-x-[12%] top-1/2 h-2 -rotate-6 rounded-full bg-white shadow"><div className="road-pattern h-full" /></div>{optimized.stops.map((stop,index)=><div key={stop.id} className="absolute" style={{left:`${15+index*22}%`,top:`${62-index*9}%`}}><span className={`grid h-9 w-9 place-items-center rounded-full border-4 border-white text-xs font-black text-white shadow-lg ${stop.status === "completed" ? "bg-success" : stop.status === "arrived" ? "bg-primary" : "bg-black"}`}>{index+1}</span><p className="mt-1 whitespace-nowrap rounded bg-white/90 px-2 py-1 text-[10px] font-black shadow">{stop.name}</p></div>)}<div className="absolute bottom-3 left-3 rounded-lg bg-black p-3 text-white shadow"><p className="text-xs font-black text-primary">Position véhicule</p><p className="text-sm font-bold">{state.gps.position.label} · {state.gps.speedKph} km/h</p></div></div></Panel><div className="grid content-start gap-4"><Metric label="Distance restante" value="38,2 km" detail="jusqu’au Hub DSS" /><Metric label="ETA" value="18:42" detail={`${delay.minutes} min de marge`} tone="success" /><Panel title="Instruction"><div className="flex gap-3"><Compass className="h-9 w-9 shrink-0 text-primary" /><div><p className="font-black">Continuez sur 450 m</p><p className="text-sm text-muted-foreground">Puis tournez à droite vers Unité 15.</p></div></div></Panel><Panel title="Sécurité"><p className="text-sm font-semibold text-muted-foreground">Les interactions sont limitées pendant la conduite. Les alertes critiques restent vocales.</p></Panel></div></div>
  </div>;
}

function VehiclePage({ state }: { state: CollectionState }) { return <div className="grid gap-5"><PageHeader eyebrow={state.vehicle.plate} title="État du véhicule" subtitle={`${state.vehicle.model} · capacité ${state.vehicle.capacityKg} kg · inspection avant départ`} actions={<Badge tone={state.vehicle.status === "ready" ? "success" : "warning"}>{state.vehicle.status}</Badge>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Charge" value={`${state.vehicle.loadKg} kg`} detail={`${Math.round(state.vehicle.loadKg/state.vehicle.capacityKg*100)}% capacité`} /><Metric label="Carburant" value={`${state.vehicle.fuelPercent}%`} detail="510 km estimés" tone="success" /><Metric label="Kilométrage" value={state.vehicle.mileageKm.toLocaleString("fr-FR")} detail="compteur vérifié" /><Metric label="Révision" value={`${state.vehicle.nextMaintenanceKm-state.vehicle.mileageKm} km`} detail="maintenance préventive" tone="warning" /></div><Panel title="Inspection chauffeur"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{state.vehicle.inspectionItems.map((item)=><div key={item.label} className={`flex items-center gap-3 rounded-lg border p-3 ${item.ok ? "bg-success/5" : "bg-warning/10"}`}>{item.ok ? <CheckCircle2 className="h-5 w-5 text-success" /> : <AlertTriangle className="h-5 w-5 text-warning" />}<span className="font-bold">{item.label}</span></div>)}</div></Panel></div>; }
function VehicleSummary({ state }: { state: CollectionState }) { const v=state.vehicle; return <div className="grid gap-3"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-black text-primary"><Truck className="h-6 w-6" /></span><div><p className="font-black">{v.model}</p><p className="text-sm text-muted-foreground">{v.plate} · {v.status}</p></div></div><div className="grid grid-cols-3 gap-2 text-center">{[[`${v.fuelPercent}%`,"Carburant"],[`${v.loadKg} kg`,"Charge"],["91/100","Éco-score"]].map(([value,label])=><div className="rounded-lg bg-muted p-3" key={label}><p className="font-black">{value}</p><p className="text-[10px] uppercase text-muted-foreground">{label}</p></div>)}</div><Link href="/collection/vehicle" className="text-sm font-black text-primary">Inspection complète →</Link></div>; }

function GenericModule({ moduleKey, copy, session, state }: { moduleKey: string; copy: typeof moduleCopy[string]; session: CollectionSession; state: CollectionState }) {
  const { formatDate } = useLocalization();
  if (moduleKey === "settings") return <div className="grid gap-5"><PageHeader eyebrow="Préférences" title="Paramètres" subtitle="Réglez l’affichage et les formats utilisés sur cet appareil." /><ExperienceSettingsPanel /></div>;
  const anomalies=detectOperationalAnomalies(state.missions[0]); const icons: Record<string, typeof Bot> = { assignment: Bot, "route-optimization": Route, quantities: PackageCheck, batches: Boxes, photos: Camera, signatures: Signature, incidents: AlertTriangle, anomalies: Sparkles, maintenance: Truck, mileage: Gauge, fuel: Fuel, offline: CloudOff, sync: RefreshCw, support: ShieldCheck, profile: CircleGauge, settings: ShieldCheck };
  const Icon=icons[moduleKey] ?? Wifi;
  const rows = moduleKey === "notifications" ? state.notifications.map((item)=>({title:item.title,detail:item.message,meta:formatDate(item.at)})) : moduleKey === "messages" ? state.messages.map((item)=>({title:item.sender,detail:item.message,meta:formatDate(item.at)})) : moduleKey === "incidents" ? state.incidents.map((item)=>({title:item.title,detail:`${item.missionCode} · ${item.status}`,meta:formatDate(item.at)})) : moduleKey === "history" ? state.events.map((item)=>({title:item.action,detail:`${item.entity} · ${item.detail}`,meta:formatDate(item.at)})) : copy.highlights.map((item,index)=>({title:item,detail:index===0 && anomalies[0] ? anomalies[0] : "Contrôle opérationnel disponible et audité.",meta:index===0 ? "Action recommandée" : "Conforme"}));
  return <div className="grid gap-5"><PageHeader eyebrow={copy.eyebrow} title={copy.title} subtitle={copy.subtitle} actions={<Badge tone="success"><ShieldCheck className="mr-1 h-3.5 w-3.5" />{session.role}</Badge>} /><div className="grid gap-3 sm:grid-cols-3">{copy.metrics.map(([label,value,detail],index)=><Metric key={label} label={label} value={value} detail={detail} tone={index===0 && (moduleKey==="incidents" || moduleKey==="anomalies") ? "warning" : index===0 ? "success" : "neutral"} />)}</div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Vue opérationnelle"><div className="grid gap-3">{rows.map((row,index)=><div key={`${row.title}-${index}`} className="flex items-start gap-3 rounded-lg border p-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-black text-primary"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-black">{row.title}</p><p className="mt-1 text-sm text-muted-foreground">{row.detail}</p></div><span className="text-right text-xs font-bold text-muted-foreground">{row.meta}</span></div>)}</div></Panel><Panel title="Points de contrôle"><div className="rounded-xl bg-black p-4 text-white"><div className="flex items-center gap-2 text-primary"><Sparkles className="h-5 w-5" /><p className="font-black">À vérifier maintenant</p></div><p className="mt-2 text-sm text-white/70">Commencez par les éléments prioritaires, puis confirmez leur traitement dans cette vue.</p></div><div className="mt-4 grid gap-2">{copy.highlights.map((item)=><div className="flex items-center gap-2 text-sm font-bold" key={item}><CheckCircle2 className="h-4 w-4 text-success" />{item}</div>)}</div><button className="mt-5 inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-black text-white"><RefreshCw className="h-4 w-4" />Actualiser la vue</button></Panel></div></div>;
}
