import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Tone } from "../lib/types";

const tones: Record<Tone, string> = { neutral: "border-border bg-background text-foreground", success: "border-success/25 bg-success/10 text-success", warning: "border-warning/40 bg-warning/15 text-foreground", danger: "border-error/25 bg-error/10 text-error", info: "border-info/25 bg-info/10 text-info" };
export function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: Tone }) { return <span className={cn("inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-black", tones[tone])}>{children}</span>; }
export function Panel({ children, title, action, className }: { children: React.ReactNode; title?: string; action?: React.ReactNode; className?: string }) { return <section className={cn("yb-panel collection-reveal", className)}>{title ? <div className="mb-4 flex items-center justify-between gap-3"><h2 className="yb-panel-title">{title}</h2>{action}</div> : null}{children}</section>; }
export function PageHeader({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions?: React.ReactNode }) { return <header className="yb-page-hero"><div className="collection-grid absolute inset-0 opacity-30" /><div className="road-pattern absolute inset-x-0 bottom-4 h-1 opacity-70" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.22em] text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{title}</h1><p className="yb-page-hero-description mt-3 text-sm md:text-base">{subtitle}</p></div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div></header>; }
export function Metric({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: Tone }) { return <Panel className={cn(tone === "danger" && "border-error/30", tone === "success" && "border-success/30")}><p className="text-xs font-black uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">{detail}</p></Panel>; }
export function ActionLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <Link href={href} className={cn("yb-button", secondary ? "border-white/25 bg-white/10 text-white hover:bg-white/15" : "yb-button-primary")}>{children}<ArrowRight className="h-4 w-4" /></Link>; }
export const inputClass = "yb-field text-sm font-semibold";
