import Link from "next/link";
import { AlertTriangle, ArrowRight, BadgeCheck, BookOpenCheck, Building2, CheckCircle2, CircleDot, Clock3, ShieldCheck, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { canAccessDirection } from "../lib/auth";
import { calculateSlaState, defaultWorkflows } from "../lib/workflow-engine";
import { canManageMissions, getGovernanceDirectionBySlug, getGovernanceRole, getGovernanceService, rolesForService, servicesForDirection, type GovernanceDirection } from "../lib/governance-catalog";
import type { AdminSession, AuditSummary, MissionSummary, TeamMemberSummary } from "../lib/types";
import { MissionForm } from "./mission-form";
import { MissionActions } from "./mission-actions";

type CommandData = { missions: MissionSummary[]; audit: AuditSummary[]; staff: TeamMemberSummary[]; sourceReady: boolean };

export function CommandDashboard({ data, directions, session }: { data: CommandData; directions: GovernanceDirection[]; session: AdminSession }) {
  const open = data.missions.filter((item) => !["closed", "cancelled"].includes(item.status));
  const atRisk = open.filter((item) => ["at_risk", "breached"].includes(calculateSlaState(item.dueAt, null)));
  const awaiting = open.filter((item) => item.status === "awaiting_validation");
  return <Page title="Centre de commandement" eyebrow="Pilotage organisationnel" description="Une vue commune des responsabilités, délais, dépendances et décisions de votre périmètre.">
    {!data.sourceReady ? <Notice /> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Missions actives" value={open.length} icon={CircleDot} /><Metric label="À valider" value={awaiting.length} icon={BadgeCheck} /><Metric label="Délais à surveiller" value={atRisk.length} icon={Clock3} /><Metric label="Collaborateurs affectés" value={data.staff.length || session.assignments.length} icon={Users} /></section>
    <section><SectionTitle eyebrow="Organisation" title="Vos directions" description="Chaque espace affiche uniquement les services et missions relevant de votre responsabilité." /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{directions.map((direction) => <Link key={direction.id} href={`/command/directions/${direction.slug}`} className="group rounded-xl border bg-background p-5 shadow-line transition hover:-translate-y-1 hover:border-primary"><span className="grid h-11 w-11 place-items-center rounded-xl text-white" style={{ backgroundColor: direction.color }}><Building2 className="h-5 w-5" /></span><h3 className="mt-5 text-xl font-black">{direction.label}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{direction.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-primary">Ouvrir l’espace <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section>
    <section><SectionTitle eyebrow="Priorités" title="Missions nécessitant une attention" description="Les validations et risques de délai sont remontés automatiquement." /><MissionList missions={[...atRisk, ...awaiting.filter((item) => !atRisk.includes(item))].slice(0, 8)} /></section>
  </Page>;
}

export function DirectionPage({ data, session, slug }: { data: CommandData; session: AdminSession; slug: string }) {
  const direction = getGovernanceDirectionBySlug(slug); if (!direction || !canAccessDirection(session, direction.id)) notFound();
  const services = servicesForDirection(direction.id);
  const missions = data.missions.filter((item) => item.directionId === direction.id);
  return <Page title={direction.label} eyebrow="Espace métier" description={direction.description} accent={direction.color}>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => { const roles = rolesForService(service.id); const active = missions.filter((item) => item.serviceId === service.id && !["closed", "cancelled"].includes(item.status)).length; return <article key={service.id} className="rounded-xl border bg-background p-5 shadow-line"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.13em] text-primary">{service.missionLabel}</p><h2 className="mt-1 text-xl font-black">{service.label}</h2></div><span className="rounded-full bg-accent px-3 py-1 text-xs font-black">{active} active{active > 1 ? "s" : ""}</span></div><p className="mt-5 text-xs font-black uppercase text-muted-foreground">Responsabilités</p><ul className="mt-2 grid gap-2 text-sm">{roles.map((role) => <li key={role.id} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-success" />{role.label}</li>)}</ul></article>; })}</section>
    <section><SectionTitle eyebrow="Exécution" title="Missions de la direction" description="Les agents ne voient que les missions attribuées dans leur périmètre." /><MissionList missions={missions} /></section>
  </Page>;
}

export function MissionsPage({ data, session }: { data: CommandData; session: AdminSession }) {
  const manager = canManageMissions(session.roleIds);
  return <Page title="Missions" eyebrow="Exécution opérationnelle" description="Créer, assigner, suivre, corriger, valider et clôturer chaque responsabilité métier.">
    <div className={manager ? "grid gap-6 xl:grid-cols-[420px_1fr]" : "grid gap-6"}>{manager ? <MissionForm /> : null}<section><SectionTitle eyebrow="File de travail" title={manager ? "Missions de votre périmètre" : "Mes missions attribuées"} description="Chaque changement est contrôlé par le workflow et ajouté au journal des décisions." /><MissionList missions={data.missions} /></section></div>
  </Page>;
}

export function WorkflowsPage({ session }: { session: AdminSession }) {
  const manager = canManageMissions(session.roleIds);
  return <Page title="Workflows métier" eyebrow="Orchestration configurable" description="Étapes, responsables, preuves, délais, validations et escalades composent chaque circuit de travail.">
    <div className="grid gap-5 xl:grid-cols-2">{defaultWorkflows.map((workflow) => <article key={workflow.key} className="rounded-xl border bg-background p-5 shadow-line"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.13em] text-primary">Version {workflow.version}</p><h2 className="mt-1 text-xl font-black">{workflow.label}</h2></div>{manager ? <span className="rounded-full bg-accent px-3 py-1 text-xs font-black">Configurable</span> : null}</div><ol className="mt-5 grid gap-3">{workflow.steps.map((step, index) => <li key={step.key} className="grid grid-cols-[34px_1fr_auto] items-center gap-3 rounded-lg bg-muted p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-black text-xs font-black text-white">{index + 1}</span><div><p className="font-black">{step.label}</p><p className="text-xs text-muted-foreground">Preuves : {step.proofTypes.length ? step.proofTypes.length : "aucune"} · validation {step.requiredValidation ? "obligatoire" : "standard"}</p></div><span className="text-xs font-black">{Math.round(step.slaMinutes / 60)} h</span></li>)}</ol></article>)}</div>
  </Page>;
}

export function TeamsPage({ data, session }: { data: CommandData; session: AdminSession }) {
  const members = data.staff.length ? data.staff : session.assignments.map((item, index) => ({ id: item.id || String(index), name: session.name, email: session.email, roleId: item.roleId, directionId: item.directionId, serviceId: item.serviceId, countryCode: item.countryCode || "SN", regionCode: item.regionCode || null }));
  return <Page title="Équipes et affectations" eyebrow="Responsabilités" description="Chaque collaborateur est relié à son métier, son service et son périmètre opérationnel."><div className="overflow-hidden rounded-xl border bg-background shadow-line"><div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><thead className="bg-black text-white"><tr>{["Collaborateur", "Rôle", "Service", "Pays / région", "État"].map((item) => <th key={item} className="px-4 py-3 font-black">{item}</th>)}</tr></thead><tbody>{members.map((member) => <tr key={member.id} className="border-t"><td className="px-4 py-4"><p className="font-black">{member.name}</p><p className="text-xs text-muted-foreground">{member.email}</p></td><td className="px-4 py-4 font-bold">{getGovernanceRole(member.roleId)?.label || "Responsabilité interne"}</td><td className="px-4 py-4">{getGovernanceService(member.serviceId)?.label || "Service Yobalelma"}</td><td className="px-4 py-4">{member.countryCode}{member.regionCode ? ` · ${member.regionCode}` : ""}</td><td className="px-4 py-4"><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">Actif</span></td></tr>)}</tbody></table></div></div></Page>;
}

export function AuditPage({ audit }: { audit: AuditSummary[] }) {
  return <Page title="Journal des décisions" eyebrow="Traçabilité" description="Toutes les affectations, transitions, corrections, validations et clôtures sont conservées."><div className="grid gap-3">{audit.length ? audit.map((item) => <article key={item.id} className="flex gap-4 rounded-xl border bg-background p-4 shadow-line"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-black text-primary"><ShieldCheck className="h-5 w-5" /></span><div className="min-w-0"><p className="font-black">{actionLabel(item.action)}</p><p className="mt-1 text-sm text-muted-foreground">{item.actorName} · {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</p>{item.note ? <p className="mt-2 text-sm">{item.note}</p> : null}</div></article>) : <Empty title="Aucune décision enregistrée" description="Les actions apparaîtront ici dès l’exécution d’une mission." />}</div></Page>;
}

export function MissionDetailPage({ canManage, detail, staff }: { canManage: boolean; detail: NonNullable<Awaited<ReturnType<typeof import("../lib/admin-data").loadMissionDetail>>>; staff: TeamMemberSummary[] }) {
  const { mission, events, proofs } = detail;
  const service = getGovernanceService(mission.serviceId);
  return <Page title={mission.title} eyebrow={mission.reference} description={mission.description}>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-xl border bg-background p-5 shadow-line"><p className="text-xs font-black uppercase text-muted-foreground">État</p><div className="mt-3"><Status value={mission.status} /></div></article><article className="rounded-xl border bg-background p-5 shadow-line"><p className="text-xs font-black uppercase text-muted-foreground">Service</p><p className="mt-3 font-black">{service?.label || "Service Yobalelma"}</p></article><article className="rounded-xl border bg-background p-5 shadow-line"><p className="text-xs font-black uppercase text-muted-foreground">Responsable</p><p className="mt-3 font-black">{mission.assigneeName || "À assigner"}</p></article><article className="rounded-xl border bg-background p-5 shadow-line"><p className="text-xs font-black uppercase text-muted-foreground">Échéance</p><p className="mt-3 font-black">{mission.dueAt ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(mission.dueAt)) : "Selon workflow"}</p></article></section>
    <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><MissionActions missionId={mission.id} status={mission.status as import("../lib/workflow-engine").MissionStatus} canManage={canManage} members={staff.filter((item) => item.serviceId === mission.serviceId).map((item) => ({ id: item.id, name: item.name }))} /><div className="grid gap-6"><section className="rounded-xl border bg-background p-5 shadow-line"><h2 className="text-xl font-black">Preuves obligatoires</h2><div className="mt-4 grid gap-2">{proofs.length ? proofs.map((proof) => <div key={proof.id} className="rounded-lg bg-muted p-3"><p className="font-black">{proof.proof_type}</p><p className="mt-1 text-sm text-muted-foreground">{proof.reference} · {proof.submitted_by_name}</p></div>) : <p className="text-sm text-muted-foreground">Aucune preuve transmise pour le moment.</p>}</div></section><section className="rounded-xl border bg-background p-5 shadow-line"><h2 className="text-xl font-black">Historique de la mission</h2><div className="mt-4 grid gap-3">{events.map((event) => <div key={event.id} className="flex gap-3 border-l-2 border-primary pl-4"><div><p className="font-black">{actionLabel(event.action)}</p><p className="text-xs text-muted-foreground">{event.actor_name} · {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.created_at))}</p>{event.note ? <p className="mt-1 text-sm">{event.note}</p> : null}</div></div>)}</div></section></div></div>
  </Page>;
}

export function Page({ accent, children, description, eyebrow, title }: { accent?: string; children: React.ReactNode; description: string; eyebrow: string; title: string }) { return <div className="command-reveal grid gap-6 md:gap-8"><header className="yb-page-hero"><div className="command-grid absolute inset-0 opacity-30" /><div className="relative"><span className="inline-flex min-h-8 items-center rounded-full px-3 py-1 text-xs font-black uppercase tracking-[.12em] text-white" style={{ backgroundColor: accent || "#b83d00" }}>{eyebrow}</span><h1 className="mt-4 max-w-4xl text-3xl font-black tracking-tight md:text-5xl">{title}</h1><p className="yb-page-hero-description mt-4">{description}</p></div></header>{children}</div>; }
function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number }) { return <article className="rounded-xl border bg-background p-5 shadow-line"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent text-primary"><Icon className="h-5 w-5" /></span><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-sm font-bold text-muted-foreground">{label}</p></article>; }
function SectionTitle({ description, eyebrow, title }: { description: string; eyebrow: string; title: string }) { return <div className="mt-2"><p className="text-xs font-black uppercase tracking-[.15em] text-primary">{eyebrow}</p><h2 className="mt-1 text-2xl font-black">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>; }
function MissionList({ missions }: { missions: MissionSummary[] }) { return <div className="mt-5 grid gap-3">{missions.length ? missions.map((mission) => { const sla = calculateSlaState(mission.dueAt, ["closed", "cancelled"].includes(mission.status) ? mission.createdAt : null); return <article key={mission.id} className="grid gap-4 rounded-xl border bg-background p-4 shadow-line md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black text-primary">{mission.reference}</span><Status value={mission.status} /><Sla value={sla} /></div><h3 className="mt-2 text-lg font-black">{mission.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{mission.description}</p><p className="mt-3 text-xs font-bold">{getGovernanceService(mission.serviceId)?.label || "Service Yobalelma"} · {mission.assigneeName || "À assigner"}</p></div><Link className="inline-flex h-10 items-center justify-center rounded-lg border px-4 text-sm font-black hover:bg-black hover:text-white" href={`/command/missions/${mission.id}`}>Consulter</Link></article>; }) : <Empty title="Aucune mission dans cette file" description="Les nouvelles responsabilités apparaîtront automatiquement selon votre périmètre." />}</div>; }
function Status({ value }: { value: string }) { const labels: Record<string, string> = { draft: "Brouillon", assigned: "Assignée", in_progress: "En cours", awaiting_validation: "À valider", correction_required: "Correction demandée", validated: "Validée", closed: "Clôturée", cancelled: "Annulée" }; return <span className="yb-status">{labels[value] || "En traitement"}</span>; }
function Sla({ value }: { value: ReturnType<typeof calculateSlaState> }) { const labels = { completed: "Terminée", on_track: "Dans les délais", at_risk: "Délai à surveiller", breached: "Délai dépassé" }; const warning = value === "at_risk" || value === "breached"; return <span className="yb-status" data-tone={warning ? "warning" : "success"}>{warning ? <AlertTriangle className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}{labels[value]}</span>; }
function Empty({ description, title }: { description: string; title: string }) { return <div className="rounded-xl border border-dashed bg-muted/40 p-8 text-center"><BookOpenCheck className="mx-auto h-8 w-8 text-primary" /><h3 className="mt-3 font-black">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>; }
function Notice() { return <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">Les indicateurs opérationnels seront actualisés dès que le service de suivi sera disponible. Les responsabilités et workflows restent consultables.</div>; }
function actionLabel(action: string) { const labels: Record<string, string> = { created: "Mission créée", assigned: "Mission assignée", reassigned: "Mission réassignée", started: "Exécution démarrée", submitted: "Mission soumise au contrôle", correction_requested: "Correction demandée", validated: "Mission validée", closed: "Mission clôturée", cancelled: "Mission annulée" }; return labels[action] || "Décision enregistrée"; }
