import Link from "next/link";
import {Activity,AlertTriangle,BrainCircuit,Building2,CircleDollarSign,CloudOff,MessageSquareWarning,PackageCheck,Radio,Route,ShieldCheck,Users} from "lucide-react";
import {Page} from "./command-pages";
import {OperationalMap,type OperationalMapAsset} from "./operational-map";
import {OperationalTimeline} from "./operational-timeline";

type Data=NonNullable<Awaited<ReturnType<typeof import("../lib/control-tower-data").loadControlTowerData>>>;
const views=["supervision","dispatch","executive","finance","support","partner","customs","operations"] as const;
const labels:Record<(typeof views)[number],string>={supervision:"Supervision",dispatch:"Dispatch",executive:"Direction générale",finance:"Finance",support:"Support",partner:"Partenaires",customs:"Douanes",operations:"Exploitation"};

export function ControlTowerPage({data}:{data:Data}){
  const assets=[
    ...data.hubs.map((item)=>asset(text(item.id),"Hub",text(item.name),text(item.city),item.latitude,item.longitude,item.is_active?"Actif":"Inactif",undefined,[{label:"Pays",value:text(item.country)}])),
    ...data.relays.map((item)=>asset(text(item.id),"Relais",text(item.name),text(item.city),item.latitude,item.longitude,text(item.status),undefined,[{label:"Capacité",value:unit(item.capacity_slots,"emplacements")},{label:"Disponibilité",value:text(item.availability)}])),
    ...data.positions.map((item)=>asset(text(item.profile_id),"Chauffeur",short(text(item.profile_id)),"Mission active",item.latitude,item.longitude,text(item.location_status),text(item.recorded_at),[{label:"Précision GPS",value:unit(item.accuracy_meters,"m")},{label:"Mission",value:short(text(item.mission_id)||"—")},{label:"Véhicule",value:short(text(item.vehicle_id)||"—")}])) ,
    ...data.positions.filter((item)=>item.vehicle_id).map((item)=>asset(text(item.vehicle_id),"Véhicule",short(text(item.vehicle_id)),"Mission active",item.latitude,item.longitude,text(item.location_status),text(item.recorded_at),[{label:"Chauffeur",value:short(text(item.profile_id))},{label:"Mission",value:short(text(item.mission_id)||"—")}])) ,
  ].filter((item):item is OperationalMapAsset=>item!==null);
  return <Page eyebrow="Global Operations" title="Control Tower" description="État du réseau, priorités et décisions de votre périmètre. Chaque indicateur provient d’une source opérationnelle autorisée et affiche sa fraîcheur.">
    {!data.sourceReady?<Notice icon={CloudOff} text="Certaines sources opérationnelles ne répondent pas. Les valeurs absentes ne sont pas remplacées par des données simulées."/>:null}
    <section className="flex flex-wrap gap-2" aria-label="Vues métier">{views.filter((view)=>data.allowedViews.includes(view)).map((view)=><Link key={view} className={`yb-status min-h-10 px-4 ${data.view===view?"bg-black text-white":""}`} href={`/command/control-tower?view=${view}${data.country?`&country=${data.country}`:""}`}>{labels[view]}</Link>)}</section>
    <form action="/command/passports" className="yb-panel grid gap-3 md:grid-cols-[1fr_auto]"><label className="grid gap-2"><span className="yb-eyebrow">Recherche universelle colis</span><input className="min-h-11 rounded-xl border bg-background px-4" name="query" placeholder="Numéro de suivi ou identifiant expédition" required /></label><button className="min-h-11 self-end rounded-xl bg-black px-5 font-black text-white" type="submit">Ouvrir le Passeport</button></form>
    <SourceFreshness sources={data.freshness}/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={Activity} label="Santé réseau" value={`${data.health.score}/100`} detail={data.health.status}/><Kpi icon={PackageCheck} label="Expéditions actives" value={data.kpis.activeShipments} detail="dans le périmètre"/><Kpi icon={Route} label="Missions actives" value={data.kpis.activeMissions} detail={`${data.kpis.onlineDrivers} chauffeur(s) en ligne`}/><Kpi icon={AlertTriangle} label="Incidents" value={data.kpis.openIncidents} detail={`${data.kpis.criticalAlerts} alerte(s) critique(s)`}/><Kpi icon={Building2} label="Capacité Hub" value={`${data.kpis.hubCapacityPercent}%`} detail="réservation agrégée"/></section>
    <div className="grid gap-5 2xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,.55fr)]"><OperationalMap assets={assets} providerConfigured={data.mapConfigured}/><Priorities data={data}/></div>
    <RoleView data={data}/>
    <div className="grid gap-5 xl:grid-cols-2"><Recommendations data={data}/><CrisisCenter data={data}/></div>
    <OperationalTimeline events={data.events}/>
    <div className="grid gap-5 xl:grid-cols-2"><Table title="Incidents et alertes" headers={["Référence","Priorité","État","Sujet","Mise à jour"]} rows={data.incidents.map((item)=>[text(item.incident_code),status(text(item.priority)),status(text(item.status)),text(item.title),date(text(item.updated_at))])}/><Table title="Digital Twin versionné" headers={["Type","Entité","Ville","État","Observation"]} rows={data.twins.map((item)=>[text(item.entity_type),short(text(item.entity_id)),text(item.city)||"—",status(text(item.operational_status)),date(text(item.observed_at))])}/></div>
    <CommunicationCenter data={data}/>
    <ModuleHealth data={data}/>
  </Page>;
}

function SourceFreshness({sources}:{sources:Data["freshness"]}){return <section className="grid gap-2 sm:grid-cols-2 xl:grid-cols-6" aria-label="Fraîcheur des sources">{sources.map((source)=><article className="rounded-xl border bg-background p-3" key={source.name}><div className="flex items-center justify-between gap-2"><p className="text-xs font-black">{source.name}</p><span className="h-2.5 w-2.5 rounded-full" data-tone={source.status} style={{backgroundColor:source.status==="realtime"?"#16a34a":source.status==="delayed"?"#f59e0b":"#dc2626"}}/></div><p className="mt-2 text-xs text-muted-foreground">{source.status==="realtime"?"Temps réel":source.status==="delayed"?"Différée":"Indisponible"} · {source.count}</p><p className="mt-1 text-[11px] text-muted-foreground">{source.updatedAt?date(source.updatedAt):"Aucun horodatage"}</p></article>)}</section>}
function Priorities({data}:{data:Data}){return <section className="yb-panel"><p className="yb-eyebrow">À comprendre maintenant</p><h2 className="text-2xl font-black">Priorités réseau</h2><div className="mt-4 grid gap-3">{data.attention.length?data.attention.map((item,index)=><article className="rounded-xl border p-4" key={item.key}><div className="flex items-center justify-between gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-black text-xs font-black text-white">{index+1}</span><strong className="text-2xl">{item.value}</strong></div><p className="mt-3 font-black">{item.label}</p></article>):<Empty icon={ShieldCheck} title="Réseau sans priorité critique" text="Aucun signal disponible ne dépasse les seuils de vigilance."/>}</div></section>}

function RoleView({data}:{data:Data}){
  if(data.view==="executive")return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ExecutiveMetric label="Taux de missions actives" value={ratio(data.kpis.activeMissions,data.kpis.activeShipments)} detail="missions / expéditions actives"/><ExecutiveMetric label="Chauffeurs connectés" value={ratio(data.kpis.onlineDrivers,data.kpis.onlineDrivers+data.kpis.staleDrivers)} detail="signal terrain frais"/><ExecutiveMetric label="Risque réseau" value={data.health.status} detail={data.health.reasons[0]??"Aucun risque prioritaire"}/><ExecutiveMetric label="Capacité hubs" value={`${data.kpis.hubCapacityPercent}%`} detail="occupation agrégée disponible"/></section>;
  if(data.view==="finance")return <Table title="Finance · Exceptions" headers={["Transaction","État","Montant","Devise","Mise à jour"]} rows={data.payments.map((item)=>[short(text(item.id)),status(text(item.status)),text(item.amount),text(item.currency),date(text(item.updated_at))])}/>;
  if(data.view==="customs")return <Table title="Douanes · Dossiers" headers={["Dossier","Expédition","Pays","État","Mise à jour"]} rows={data.customs.map((item)=>[short(text(item.id)),short(text(item.shipment_id)),text(item.country_scope),status(text(item.status)),date(text(item.updated_at))])}/>;
  if(data.view==="support")return <Table title="Support · Incidents" headers={["Incident","Sujet","Priorité","État","Assignation"]} rows={data.incidents.map((item)=>[text(item.incident_code),text(item.title),status(text(item.priority)),status(text(item.status)),short(text(item.assigned_to)||"À assigner")])}/>;
  if(data.view==="partner")return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><External label="Orange Money" active={data.external.orangeMoney}/><External label="Notifications" active={data.external.notifications}/><External label="WhatsApp" active={data.external.whatsapp}/><External label="Cartographie" active={data.external.maps}/></section><Table title="Périmètre relais partenaire autorisé" headers={["Relais","Ville","Pays","État","Capacité"]} rows={data.relays.map((item)=>[text(item.name),text(item.city),text(item.country),status(text(item.status)),unit(item.capacity_slots,"emplacements")])}/></>;
  return <div className="grid gap-5 xl:grid-cols-2"><Table title="Flux d’expéditions" headers={["Expédition","Origine","Destination","État","Mise à jour"]} rows={data.shipments.map((item)=>[short(text(item.id)),`${text(item.origin_city)} · ${text(item.origin_country)}`,`${text(item.destination_city)} · ${text(item.destination_country)}`,status(text(item.status)),date(text(item.updated_at))])}/><Table title="Équipes terrain" headers={["Agent","Statut","Mission","Tournée","Mise à jour"]} rows={data.driverStates.map((item)=>[short(text(item.profile_id)),status(text(item.status)),short(text(item.active_mission_id)||"—"),short(text(item.collection_route_id)||"—"),date(text(item.updated_at))])}/></div>;
}

function Recommendations({data}:{data:Data}){const rows=data.storedRecommendations.length?data.storedRecommendations:data.derivedRecommendations;return <section className="yb-panel"><div className="flex items-center gap-3"><BrainCircuit className="h-6 w-6 text-primary"/><div><p className="yb-eyebrow">AI Decision Center</p><h2 className="text-xl font-black">Recommandations expliquées</h2></div></div><div className="mt-4 grid gap-3">{rows.length?rows.slice(0,6).map((raw,index)=>{const item=raw as Record<string,unknown>;const alternatives=Array.isArray(item.alternatives)?item.alternatives:[];return <article className="rounded-xl border p-4" key={`${text(item.type??item.recommendation_type)}-${index}`}><div className="flex flex-wrap items-center justify-between gap-3"><strong>{text(item.title)}</strong><div className="flex gap-2">{item.confidence!==undefined?<span className="yb-status">Confiance {text(item.confidence)}%</span>:null}<span className="yb-status" data-tone="warning">Validation humaine</span></div></div><p className="mt-2 text-sm text-muted-foreground">{text(item.explanation)}</p>{alternatives.length?<p className="mt-3 text-xs"><strong>Alternatives :</strong> {alternatives.map(text).join(" · ")}</p>:null}{item.expires_at?<p className="mt-2 text-xs text-muted-foreground">Expire le {date(text(item.expires_at))}</p>:null}</article>}):<Empty icon={BrainCircuit} title="Aucune recommandation" text="Le moteur n’ajoute rien sans signal vérifiable."/>}</div></section>}
function CrisisCenter({data}:{data:Data}){const crises=data.incidents.filter((item)=>["urgent","critical"].includes(text(item.priority))&&!['resolved','closed'].includes(text(item.status)));return <section className="yb-panel"><div className="flex items-center gap-3"><MessageSquareWarning className="h-6 w-6 text-primary"/><div><p className="yb-eyebrow">Crisis Center</p><h2 className="text-xl font-black">Situations majeures</h2></div></div><div className="mt-4 grid gap-3">{crises.length?crises.slice(0,6).map((item)=><article className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-950" key={text(item.id)}><div className="flex flex-wrap justify-between gap-2"><strong>{text(item.title)}</strong>{status(text(item.status))}</div><p className="mt-2 text-sm">{text(item.incident_code)} · {text(item.city)||text(item.country_code)} · ouvert {date(text(item.created_at))}</p><p className="mt-2 text-xs">Responsable : {short(text(item.assigned_to)||"Non assigné")} · journal de décision conservé côté serveur</p></article>):<Empty icon={ShieldCheck} title="Mode crise inactif" text="Aucun incident urgent ou critique ouvert dans le périmètre autorisé."/>}</div></section>}
function CommunicationCenter({data}:{data:Data}){const byChannel=new Map<string,number>();for(const item of data.notifications)byChannel.set(text(item.channel)||"in_app",(byChannel.get(text(item.channel)||"in_app")??0)+1);return <section className="yb-panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="yb-eyebrow">Communication Center</p><h2 className="text-xl font-black">Livraisons et connecteurs</h2></div><span className="yb-status" data-tone={data.kpis.notificationBacklog?"warning":"success"}>{data.kpis.notificationBacklog} en attente ou en échec</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{["in_app","push","email","sms"].map((channel)=><article className="rounded-xl border p-4" key={channel}><p className="font-black">{channel.replaceAll("_"," ")}</p><p className="mt-2 text-2xl font-black">{byChannel.get(channel)??0}</p><p className="mt-1 text-xs text-muted-foreground">{channel==="in_app"||data.external.notifications?"File réelle contrôlée":"Fournisseur officiel non connecté"}</p></article>)}</div><p className="mt-3 text-xs text-muted-foreground">WhatsApp reste explicitement désactivé tant qu’un accès Business officiel et des modèles approuvés ne sont pas configurés.</p></section>}
function ModuleHealth({data}:{data:Data}){return <section className="yb-panel"><div className="flex items-center justify-between gap-3"><div><p className="yb-eyebrow">Santé technique</p><h2 className="text-xl font-black">Modules indépendants</h2></div><Radio className="h-5 w-5 text-primary"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.moduleHealth.length?data.moduleHealth.map((item)=><article className="rounded-xl border p-4" key={`${text(item.module)}-${text(item.country_code)}`}><p className="font-black">{text(item.module)}</p><p className="mt-2 text-sm">{status(text(item.status))} · backlog {text(item.backlog_count)}</p><p className="mt-1 text-xs text-muted-foreground">p95 {text(item.latency_p95_ms)||"—"} ms · dernière réussite {item.last_success_at?date(text(item.last_success_at)):"—"}</p></article>):<p className="text-sm text-muted-foreground">Les métriques apparaîtront après le premier cycle du worker Control Tower.</p>}</div></section>}
function ExecutiveMetric({detail,label,value}:{detail:string;label:string;value:string}){return <article className="yb-panel"><p className="yb-eyebrow">{label}</p><p className="mt-3 text-3xl font-black capitalize">{value}</p><p className="mt-2 text-sm text-muted-foreground">{detail}</p></article>}
function Kpi({icon:Icon,label,value,detail}:{icon:typeof Users;label:string;value:string|number;detail:string}){return <article className="yb-kpi"><Icon className="h-5 w-5 text-primary"/><p className="yb-kpi-value mt-4">{value}</p><p className="mt-1 text-sm font-black">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>}
function Table({headers,rows,title}:{headers:string[];rows:React.ReactNode[][];title:string}){return <section className="yb-panel"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr>{headers.map((header)=><th className="border-b bg-muted px-3 py-3 text-xs font-black uppercase" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr className="border-b last:border-0" key={index}>{row.map((cell,cellIndex)=><td className="px-3 py-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length?<p className="p-6 text-center text-sm text-muted-foreground">Aucune donnée dans ce périmètre.</p>:null}</div></section>}
function External({active,label}:{active:boolean;label:string}){return <article className="yb-panel"><CircleDollarSign className="h-5 w-5 text-primary"/><p className="mt-3 font-black">{label}</p><p className="mt-2 text-sm text-muted-foreground">{active?"Accès configuré":"Désactivé · accès officiel requis"}</p></article>}
function Notice({icon:Icon,text:value}:{icon:typeof CloudOff;text:string}){return <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-950"><Icon className="mr-2 inline h-4 w-4"/>{value}</div>}
function Empty({icon:Icon,text:value,title}:{icon:typeof ShieldCheck;text:string;title:string}){return <div className="rounded-xl border border-dashed p-5 text-center"><Icon className="mx-auto h-7 w-7 text-primary"/><p className="mt-2 font-black">{title}</p><p className="mt-1 text-sm text-muted-foreground">{value}</p></div>}
function status(value:string){const danger=["critical","urgent","failed","blocked","seized","rejected"].includes(value);const success=["active","available","completed","delivered","resolved","closed","nominal","online"].includes(value);return <span className="yb-status" data-tone={danger?"danger":success?"success":"warning"}>{value.replaceAll("_"," ")||"—"}</span>}
function ratio(value:number,total:number){return total?`${Math.round(value/total*100)}%`:"Indisponible"}
function text(value:unknown){return value===null||value===undefined?"":String(value)}
function num(value:unknown){const result=Number(value);return Number.isFinite(result)?result:null}
function unit(value:unknown,label:string){const parsed=num(value);return parsed===null?"—":`${parsed.toLocaleString("fr-FR")} ${label}`}
function short(value:string){return value.length>14?`${value.slice(0,8)}…${value.slice(-4)}`:value}
function date(value:string){if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"—":new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(parsed)}
function asset(id:string,type:string,name:string,city:string,latitude:unknown,longitude:unknown,statusValue:string,updatedAt?:string,details?:OperationalMapAsset["details"]):OperationalMapAsset|null{const lat=num(latitude);const lng=num(longitude);return lat===null||lng===null?null:{id:`${type}-${id}`,type,name,city,latitude:lat,longitude:lng,status:statusValue,updatedAt,details}}
