import Link from "next/link";
import { AlertTriangle, Boxes, Clock3, FileCheck2, Gavel, Scale, ShieldCheck } from "lucide-react";
import { Page } from "./command-pages";
import { customsSections, type CustomsSection } from "../lib/customs-data";

type CustomsData = NonNullable<Awaited<ReturnType<typeof import("../lib/customs-data").loadCustomsData>>>;
const labels: Record<CustomsSection, string> = { dossiers: "Dossiers douaniers", declarations: "Déclarations", documents: "Documents", marchandises: "Marchandises", inspections: "Inspections", "droits-taxes": "Droits et taxes", mainlevees: "Mainlevées", blocages: "Blocages", saisies: "Saisies", commissionnaires: "Commissionnaires", bureaux: "Bureaux de douane", "regles-pays": "Règles par pays", "codes-hs": "Codes HS", incidents: "Incidents", audit: "Audit", integrations: "Intégrations", statistiques: "Statistiques" };

export function CustomsPage({ data, section }: { data: CustomsData; section?: CustomsSection }) {
  const selected = section ?? "dossiers";
  const pending = data.cases.filter((item) => !["released", "closed", "cancelled", "rejected"].includes(item.status));
  const blocked = data.cases.filter((item) => ["suspended", "seized", "rejected"].includes(item.status));
  const missing = data.documents.filter((item) => item.status !== "verified");
  const inspections = data.cases.filter((item) => item.inspection_required || ["inspection_required", "under_inspection"].includes(item.status));
  return <Page eyebrow="Douane et commerce international" title={section ? labels[selected] : "Pilotage douanier"} description="Dossiers, preuves, décisions et obligations suivis selon le pays et le périmètre autorisé.">
    {!data.sourceReady ? <Notice text="Les données douanières ne sont pas encore disponibles dans cet environnement." /> : null}
    {!data.officialConfigured ? <Notice text="La connexion officielle n’est pas activée. Toute mainlevée reste bloquée sans décision vérifiée et preuve documentaire." /> : null}
    <nav className="flex gap-2 overflow-x-auto pb-2" aria-label="Rubriques douanières">{customsSections.map((item) => <Link className={`shrink-0 rounded-full border px-4 py-2 text-sm font-black ${selected === item ? "border-primary bg-primary text-primary-foreground" : "bg-background hover:border-primary"}`} href={`/command/douane/${item}`} key={item}>{labels[item]}</Link>)}</nav>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Dossiers en attente" value={pending.length} icon={Clock3} /><Kpi label="Documents à contrôler" value={missing.length} icon={FileCheck2} /><Kpi label="Inspections" value={inspections.length} icon={ShieldCheck} /><Kpi label="Dossiers bloqués" value={blocked.length} icon={AlertTriangle} /></section>
    <Section data={data} section={selected} />
  </Page>;
}

function Section({ data, section }: { data: CustomsData; section: CustomsSection }) {
  if (section === "documents") return <Table title="Pièces justificatives" headers={["Type", "Dossier", "Fichier", "État", "Contrôle"]} rows={data.documents.map((item) => [item.document_type, short(item.customs_case_id), item.filename, <Status key="s" value={item.status} />, date(item.verified_at ?? item.created_at)])} empty="Aucun document dans ce périmètre." />;
  if (section === "droits-taxes") return <Table title="Liquidations et estimations" headers={["Dossier", "Nature", "Montant", "Origine", "État"]} rows={data.duties.map((item) => [short(item.customs_case_id), item.duty_type, money(item.amount, item.currency), item.calculation_source === "yobalelma_indicative" ? "Estimation indicative" : "Montant officiel reçu", <Status key="s" value={item.status} />])} empty="Aucun droit ou taxe enregistré." />;
  if (section === "mainlevees" || section === "inspections" || section === "saisies") { const type = section === "mainlevees" ? "release" : section === "inspections" ? "inspection" : "seizure"; return <Table title={labels[section]} headers={["Dossier", "Décision", "Autorité", "Source", "Vérification"]} rows={data.decisions.filter((item) => item.decision_type === type).map((item) => [short(item.customs_case_id), item.decision_reference, item.authority, item.source === "official_provider" ? "Canal officiel" : "Mode contrôlé", item.verified ? "Double contrôle obtenu" : "Validation attendue"])} empty="Aucune décision correspondante." />; }
  if (section === "commissionnaires") return <Table title="Commissionnaires agréés" headers={["Organisation", "Agrément", "Pays", "SLA", "État"]} rows={data.brokers.map((item) => [item.organization_name, item.license_reference, item.license_country, item.sla_minutes ? `${item.sla_minutes} min` : "À définir", <Status key="s" value={item.status} />])} empty="Aucun commissionnaire validé." />;
  if (section === "bureaux") return <Table title="Bureaux de douane" headers={["Pays", "Code", "Nom", "État", "Vérification"]} rows={data.offices.map((item) => [item.country_code, item.office_code, item.name, <Status key="s" value={item.status} />, item.verified_at ? date(item.verified_at) : "À confirmer"])} empty="Aucun bureau officiel enregistré." />;
  if (section === "regles-pays") return <Table title="Référentiels nationaux versionnés" headers={["Pays", "Référentiel", "Version", "Validité", "État"]} rows={data.rules.map((item) => [item.country_code, item.name, `v${item.version}`, `${item.effective_from}${item.effective_to ? ` → ${item.effective_to}` : ""}`, <Status key="s" value={item.status} />])} empty="Aucune règle validée. Aucune règle légale n’est supposée par défaut." />;
  if (section === "codes-hs") return <Table title="Propositions de classification" headers={["Article", "Code proposé", "Source", "Confiance", "État"]} rows={data.hsSuggestions.map((item) => [short(item.customs_item_id), item.proposed_code, item.source, `${Math.round(Number(item.confidence) * 100)} %`, <Status key="s" value={item.status} />])} empty="Aucune proposition de code HS." />;
  if (section === "audit" || section === "incidents") { const events = section === "incidents" ? data.events.filter((item) => !item.verified || item.event_type.includes("error") || item.event_type.includes("failed")) : data.events; return <Table title={labels[section]} headers={["Dossier", "Événement", "Source", "Preuve", "Date"]} rows={events.map((item) => [short(item.customs_case_id), item.event_type, item.source, item.verified ? "Vérifié" : "À vérifier", date(item.created_at)])} empty="Aucun événement correspondant." />; }
  if (section === "integrations") return <Table title="File d’intégration officielle" headers={["Dossier", "Opération", "Tentatives", "Prochaine reprise", "État"]} rows={data.outbox.map((item) => [short(item.customs_case_id), item.operation, `${item.attempt_count}/${item.max_attempts}`, date(item.next_attempt_at), <Status key="s" value={item.status} />])} empty="Aucune opération en file. Les accès officiels restent requis pour activer le canal." />;
  const cases = section === "blocages" ? data.cases.filter((item) => ["suspended", "rejected"].includes(item.status)) : section === "declarations" ? data.cases.filter((item) => Boolean(item.declaration_reference)) : data.cases;
  return <Table title={section === "statistiques" ? "Vue consolidée des corridors" : labels[section]} headers={["Dossier", "Corridor", "Déclaration", "Risque", "État"]} rows={cases.map((item) => [short(item.shipment_id), `${item.origin_country} → ${item.destination_country}`, item.declaration_reference || "Non soumise", item.risk_level, <Status key="s" value={item.status} />])} empty="Aucun dossier dans ce périmètre." />;
}

function Table({ empty, headers, rows, title }: { empty: string; headers: string[]; rows: React.ReactNode[][]; title: string }) { return <section className="yb-panel"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-primary"><Scale className="h-5 w-5" /></span><div><p className="yb-eyebrow">Périmètre autorisé</p><h2 className="text-2xl font-black">{title}</h2></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr>{headers.map((header) => <th className="border-b bg-muted px-3 py-3 text-xs font-black uppercase" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-b last:border-0" key={index}>{row.map((cell, cellIndex) => <td className="px-3 py-4" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{empty}</p> : null}</div></section>; }
function Kpi({ icon: Icon, label, value }: { icon: typeof Boxes; label: string; value: number }) { return <article className="yb-kpi"><Icon className="h-5 w-5 text-primary" /><p className="yb-kpi-value mt-5">{value}</p><p className="mt-2 text-sm font-bold text-muted-foreground">{label}</p></article>; }
function Status({ value }: { value: string }) { const danger = ["rejected", "suspended", "seized", "failed", "dead_letter"].includes(value); const success = ["released", "closed", "verified", "validated", "completed", "paid", "official_assessed", "active"].includes(value); return <span className="yb-status" data-tone={danger ? "danger" : success ? "success" : "warning"}>{value.replaceAll("_", " ")}</span>; }
function Notice({ text }: { text: string }) { return <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-950"><Gavel className="mr-2 inline h-4 w-4" />{text}</div>; }
function short(value: string) { return value.length > 14 ? `${value.slice(0, 8)}…${value.slice(-4)}` : value; }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function money(amount: number, currency: string) { return new Intl.NumberFormat("fr-FR", { style: "currency", currency }).format(Number(amount)); }
