import { AlertTriangle, LocateFixed, MapPinned, Route, ShieldCheck, Truck } from "lucide-react";
import { Page } from "./command-pages";
type Data = NonNullable<Awaited<ReturnType<typeof import("../lib/dispatch-data").loadDispatchData>>>;
export function DispatchPage({ data }: { data: Data }) {
  const online = data.positions.filter((item) => new Date(item.expires_at).getTime()>Date.now()); const pending = data.missions.filter((item) => ["suggested", "offered"].includes(item.status));
  return <Page eyebrow="Opérations" title="Dispatch" description="Missions, équipes terrain, capacités et recommandations dans le périmètre opérationnel autorisé.">
    {!data.sourceReady ? <Notice text="Les données de dispatch ne sont pas disponibles dans cet environnement." /> : null}
    {!data.mapConfigured ? <Notice text="La carte routière et les temps de trajet restent désactivés jusqu’à l’activation d’un fournisseur cartographique. Les distances de secours ne déclenchent aucune affectation silencieuse." /> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={Route} label="Missions à traiter" value={pending.length} /><Kpi icon={LocateFixed} label="Agents suivis maintenant" value={online.length} /><Kpi icon={MapPinned} label="Relais et hubs" value={data.relays.length + data.hubs.length} /><Kpi icon={AlertTriangle} label="Alertes de suivi" value={data.trackingAlerts.length} /></section>
    <section className="yb-panel"><p className="yb-eyebrow">Filtres opérationnels</p><div className="mt-3 flex flex-wrap gap-2">{["Pays","Région","Ville","Zone","Véhicule","Statut","Mission","Hub","Relais","Retard","Disponibilité"].map((label)=><span className="yb-status" key={label}>{label}</span>)}</div><p className="mt-3 text-sm text-muted-foreground">Les filtres deviennent interactifs avec le fond cartographique et les agrégats fournisseur. Les contrôles de périmètre restent appliqués côté base.</p></section>
    <section className="yb-panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="yb-eyebrow">Carte opérationnelle</p><h2 className="text-2xl font-black">Positions autorisées</h2></div><span className="yb-status" data-tone={data.mapConfigured ? "success" : "warning"}>{data.mapConfigured ? "Fournisseur activé" : "Activation requise"}</span></div><div className="mt-5 grid min-h-64 place-items-center rounded-2xl border border-dashed bg-muted/40 p-8 text-center"><div><MapPinned className="mx-auto h-10 w-10 text-primary" /><p className="mt-3 font-black">{data.mapConfigured ? "Le fond cartographique est prêt à être rendu par le client autorisé." : "Aucun fond de carte simulé n’est affiché."}</p><p className="mt-2 max-w-xl text-sm text-muted-foreground">Les positions détaillées sont limitées aux responsables autorisés et conservées pendant une durée bornée.</p></div></div></section>
    <div className="grid gap-5 xl:grid-cols-2"><Table title="Missions" headers={["Mission", "Agent", "État", "Score", "Mise à jour"]} rows={data.missions.map((item) => [short(item.id), short(item.transporter_id), item.status, String(item.score), date(item.updated_at)])} /><Table title="Recommandations" headers={["Mission", "Candidat", "Score", "Trajet", "Contrôle"]} rows={data.recommendations.map((item) => [short(item.mission_id), short(item.candidate_profile_id), String(item.score), item.route_source === "provider" ? `${Math.round(item.distance_meters / 100) / 10} km` : "Distance provisoire", item.requires_human_approval ? "Validation requise" : item.status])} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><Table title="Équipes terrain" headers={["Agent", "État GPS", "Précision", "Réseau", "Dernier signal"]} rows={data.positions.map((item) => [short(item.profile_id),item.location_status,`${item.accuracy_meters} m`,item.network_status,date(item.recorded_at)])} /><Table title="États chauffeur" headers={["Agent","Statut","Mission ou tournée","Transition"]} rows={data.driverStates.map((item)=>[short(item.profile_id),item.status,short(item.active_mission_id??item.collection_route_id??"—"),date(item.last_transition_at)])}/></div>
    <div className="grid gap-5 xl:grid-cols-2"><Table title="Alertes de suivi" headers={["Agent","Type","Gravité","État","Détectée"]} rows={data.trackingAlerts.map((item)=>[short(item.profile_id),item.alert_type,item.severity,item.status,date(item.detected_at)])}/><Table title="Règles actives et versions" headers={["Pays", "Ville", "Version", "Mode", "État"]} rows={data.rules.map((item) => [item.country_code, item.city || "Toutes", `v${item.version}`, item.mode, item.status])} /></div>
  </Page>;
}
function Kpi({ icon: Icon, label, value }: { icon: typeof Truck; label: string; value: number }) { return <article className="yb-kpi"><Icon className="h-5 w-5 text-primary" /><p className="yb-kpi-value mt-5">{value}</p><p className="mt-2 text-sm font-bold text-muted-foreground">{label}</p></article>; }
function Notice({ text }: { text: string }) { return <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-950"><ShieldCheck className="mr-2 inline h-4 w-4" />{text}</div>; }
function Table({ headers, rows, title }: { headers: string[]; rows: React.ReactNode[][]; title: string }) { return <section className="yb-panel"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr>{headers.map((item) => <th className="border-b bg-muted px-3 py-3 text-xs font-black uppercase" key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-b last:border-0" key={index}>{row.map((cell, cellIndex) => <td className="px-3 py-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length ? <p className="p-6 text-center text-sm text-muted-foreground">Aucune donnée dans ce périmètre.</p> : null}</div></section>; }
function short(value: string) { return value.length > 14 ? `${value.slice(0, 8)}…${value.slice(-4)}` : value; } function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
