import Link from "next/link";
import { AlertTriangle, ArrowDownToLine, CheckCircle2, Clock3, RefreshCcw, Search, ShieldCheck, WalletCards } from "lucide-react";
import { Page } from "./command-pages";
import type { FinanceFilters } from "../lib/finance-data";
import { RefundRequestForm } from "./refund-request-form";

type FinanceData = NonNullable<Awaited<ReturnType<typeof import("../lib/finance-data").loadFinanceData>>>;

export function FinancePaymentsPage({ data, filters }: { data: FinanceData; filters: FinanceFilters }) {
  const pending = data.payments.filter((item) => ["created", "pending", "awaiting_customer_validation", "processing"].includes(item.status));
  const anomalies = data.payments.filter((item) => item.failure_code || item.status === "failed");
  const webhookFailures = data.events.filter((item) => item.processing_status === "failed" || !item.verified);
  return <Page eyebrow="Direction Finance" title="Paiements" description="Encaissements, confirmations fournisseur, rapprochements, anomalies et remboursements contrôlés.">
    {!data.sourceReady ? <ActivationNotice /> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Transactions" value={data.payments.length} icon={WalletCards} /><Kpi label="En attente" value={pending.length} icon={Clock3} /><Kpi label="Anomalies" value={anomalies.length} icon={AlertTriangle} /><Kpi label="Webhooks à traiter" value={webhookFailures.length} icon={RefreshCcw} /></section>
    <FilterForm filters={filters} />
    <section className="yb-panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="yb-eyebrow">File financière</p><h2 className="mt-1 text-2xl font-black">Transactions</h2></div><Link className="yb-button yb-button-secondary" href="/api/admin/finance/export"><ArrowDownToLine className="h-4 w-4" />Export comptable</Link></div><div className="mt-5 overflow-x-auto"><table className="min-w-[960px] w-full text-left text-sm"><thead><tr>{["Référence", "Colis", "Fournisseur", "Montant", "Pays", "État", "Création"].map((label) => <th className="border-b bg-muted px-3 py-3 text-xs font-black uppercase" key={label}>{label}</th>)}</tr></thead><tbody>{data.payments.map((payment) => <tr className="border-b last:border-0" key={payment.id}><td className="px-3 py-4 font-black">{payment.internal_reference}</td><td className="px-3 py-4 font-mono text-xs">{short(payment.shipment_id)}</td><td className="px-3 py-4">{payment.provider === "orange_money" ? "Orange Money" : "Adaptateur de test"}</td><td className="px-3 py-4 font-black">{money(payment.amount, payment.currency)}</td><td className="px-3 py-4">{payment.country_code}</td><td className="px-3 py-4"><Status value={payment.status} /></td><td className="px-3 py-4">{date(payment.created_at)}</td></tr>)}</tbody></table>{!data.payments.length ? <Empty text="Aucune transaction ne correspond aux filtres." /> : null}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><EventList data={data} /><RefundList data={data} /></div>
  </Page>;
}

export function FinancePayoutsPage({ data }: { data: FinanceData }) {
  const sensitive = data.payouts.filter((item) => item.approved_by && !item.second_approved_by);
  return <Page eyebrow="Direction Finance" title="Reversements" description="Montants dus, validations, commissions, reprises et historique des paiements partenaires.">
    {!data.sourceReady ? <ActivationNotice /> : null}
    <section className="grid gap-4 sm:grid-cols-3"><Kpi label="Reversements" value={data.payouts.length} icon={WalletCards} /><Kpi label="Double validation requise" value={sensitive.length} icon={ShieldCheck} /><Kpi label="Échecs" value={data.payouts.filter((item) => ["failed", "payout_failed"].includes(item.status)).length} icon={AlertTriangle} /></section>
    <section className="yb-panel"><p className="yb-eyebrow">Contrôle des sorties</p><h2 className="mt-1 text-2xl font-black">Bénéficiaires et reversements</h2><div className="mt-5 overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm"><thead><tr>{["Bénéficiaire", "Motif", "Montant", "Fournisseur", "Validation", "État", "Historique"].map((label) => <th className="border-b bg-muted px-3 py-3 text-xs font-black uppercase" key={label}>{label}</th>)}</tr></thead><tbody>{data.payouts.map((payout) => <tr className="border-b last:border-0" key={payout.id}><td className="px-3 py-4"><p className="font-black">{payout.beneficiary_type}</p><p className="font-mono text-xs text-muted-foreground">{short(payout.beneficiary_id)}</p></td><td className="px-3 py-4">{payout.reason || "Mission validée"}</td><td className="px-3 py-4 font-black">{money(payout.amount_cents, payout.currency)}</td><td className="px-3 py-4">{payout.provider === "orange_money" ? "Orange Money" : "Non activé"}</td><td className="px-3 py-4">{payout.second_approved_by ? "Double validation obtenue" : payout.approved_by ? "Seconde validation attendue" : "Validation attendue"}</td><td className="px-3 py-4"><Status value={payout.status} /></td><td className="px-3 py-4">{date(payout.completed_at || payout.initiated_at || payout.created_at)}</td></tr>)}</tbody></table>{!data.payouts.length ? <Empty text="Aucun reversement prêt à être exécuté." /> : null}</div></section>
  </Page>;
}

function FilterForm({ filters }: { filters: FinanceFilters }) { return <form className="yb-panel grid gap-3 md:grid-cols-2 xl:grid-cols-8" method="get"><label className="yb-label xl:col-span-2">Transaction, colis ou utilisateur<div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><input className="yb-field pl-10" defaultValue={filters.query} name="query" /></div></label><label className="yb-label">État<select className="yb-field" defaultValue={filters.status} name="status"><option value="">Tous</option><option value="pending">En attente</option><option value="succeeded">Réussi</option><option value="failed">Échec</option><option value="refunded">Remboursé</option></select></label><label className="yb-label">Pays<input className="yb-field" defaultValue={filters.country} maxLength={2} name="country" placeholder="SN" /></label><label className="yb-label">Devise<input className="yb-field" defaultValue={filters.currency} maxLength={3} name="currency" placeholder="XOF" /></label><label className="yb-label">Du<input className="yb-field" defaultValue={filters.from} name="from" type="date" /></label><label className="yb-label">Au<input className="yb-field" defaultValue={filters.to} name="to" type="date" /></label><button className="yb-button yb-button-primary self-end" type="submit">Appliquer</button></form>; }
function EventList({ data }: { data: FinanceData }) { return <section className="yb-panel"><p className="yb-eyebrow">Traçabilité</p><h2 className="mt-1 text-xl font-black">Événements fournisseur</h2><div className="mt-4 grid gap-2">{data.events.slice(0, 12).map((event) => <article className="rounded-xl border p-3" key={event.id}><div className="flex items-center justify-between gap-3"><p className="font-black">{event.event_type}</p><Status value={event.processing_status} /></div><p className="mt-1 text-xs text-muted-foreground">{event.verified ? "Authentifié" : "Authenticité non confirmée"} · {date(event.received_at)}</p></article>)}{!data.events.length ? <Empty text="Aucun événement fournisseur reçu." /> : null}</div></section>; }
function RefundList({ data }: { data: FinanceData }) { return <section className="yb-panel"><p className="yb-eyebrow">Autorisation</p><h2 className="mt-1 text-xl font-black">Remboursements</h2><RefundRequestForm payments={data.payments.filter((payment) => ["succeeded", "partially_refunded"].includes(payment.status)).map((payment) => ({ amount: payment.amount, currency: payment.currency, id: payment.id, reference: payment.internal_reference }))} /><div className="mt-5 grid gap-2">{data.refunds.slice(0, 12).map((refund) => <article className="rounded-xl border p-3" key={refund.id}><div className="flex items-center justify-between gap-3"><p className="font-black">{money(refund.amount, "")}</p><Status value={refund.status} /></div><p className="mt-1 text-sm">{refund.reason}</p><p className="mt-1 text-xs text-muted-foreground">{refund.approved_by ? "Autorisé" : "Autorisation requise"}</p></article>)}{!data.refunds.length ? <Empty text="Aucune demande de remboursement." /> : null}</div></section>; }
function ActivationNotice() { return <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-950">L’espace Finance est prêt, mais les opérations monétaires restent bloquées jusqu’à l’installation du schéma et à l’activation contractuelle du fournisseur.</div>; }
function Kpi({ icon: Icon, label, value }: { icon: typeof CheckCircle2; label: string; value: number }) { return <article className="yb-kpi"><Icon className="h-5 w-5 text-primary" /><p className="yb-kpi-value mt-5">{value}</p><p className="mt-2 text-sm font-bold text-muted-foreground">{label}</p></article>; }
function Status({ value }: { value: string }) { const danger = value.includes("failed") || value === "failed"; const success = value.includes("succeeded") || value === "processed" || value === "refunded"; return <span className="yb-status" data-tone={danger ? "danger" : success ? "success" : "warning"}>{value.replaceAll("_", " ")}</span>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</p>; }
function short(value: string) { return value.length > 14 ? `${value.slice(0, 8)}…${value.slice(-4)}` : value; }
function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function money(amount: number, currency: string) { return currency ? new Intl.NumberFormat("fr-FR", { style: "currency", currency }).format(amount / 100) : new Intl.NumberFormat("fr-FR").format(amount / 100); }
