export const userAppManifest = {
  domain: "app.yobalelma.com",
  id: "user-app",
  ownedRoutePrefixes: [
    "/",
    "/how-it-works",
    "/security",
    "/pricing",
    "/tracking",
    "/relay-points",
    "/prohibited-items",
    "/support",
    "/terms",
    "/privacy",
    "/auth",
    "/client",
    "/transporter",
    "/traveler",
    "/api/auth",
    "/api/profile",
    "/api/shipments",
    "/api/parcel-requests",
    "/api/transporters",
    "/api/trips",
    "/api/travel-documents"
  ],
  roles: ["client", "local_transporter", "traveler"],
  status: "active",
} as const;
