"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Archive, Boxes, Camera, KeyRound, PackageCheck, Printer, ScanLine, Search, ShieldCheck, Sparkles, Warehouse } from "lucide-react";
import { detectRelayAnomalies, forecastCapacity, locationUtilization, suggestBestLocation } from "../lib/optimizer";
import type { RelayPackage, RelaySession, RelayState, Tone } from "../lib/types";
import { ActionLink, Badge, inputClass, Metric, PageHeader, Panel } from "./relay-ui";
import { eventActionLabel, incidentSeverityLabel, incidentStatusLabel, locationKindLabel, packageStatusLabel, relayRoleLabel } from "../lib/presentation";

const labels: Record<string, { eyebrow: string; title: string; subtitle: string }> = {
  quality: { eyebrow: "Contrôle contradictoire", title: "Contrôle qualité", subtitle: "Poids, dimensions, emballage, photos et conformité sont vérifiés avant stockage." },
  weighing: { eyebrow: "Métrologie", title: "Pesée des colis", subtitle: "Compare la mesure certifiée au poids déclaré et bloque les écarts hors tolérance." },
  dimensions: { eyebrow: "Gabarit", title: "Vérification des dimensions", subtitle: "Mesure longueur, largeur et hauteur pour sécuriser la facturation et le rangement." },
  photos: { eyebrow: "Preuves", title: "Photos des colis", subtitle: "Conserve les preuves horodatées du colis, de l’étiquette et des éventuelles avaries." },
  shelves: { eyebrow: "Organisation", title: "Gestion des rayonnages", subtitle: "Visualise charge, poids admissible et occupation de chaque rayonnage." },
  lockers: { eyebrow: "Retraits sécurisés", title: "Gestion des casiers", subtitle: "Pilote les casiers OTP et leur disponibilité en temps réel." },
  labels: { eyebrow: "Étiquetage", title: "Impression d’étiquettes", subtitle: "Produit des étiquettes QR et code-barres conformes au réseau Yobalelma." },
  receipts: { eyebrow: "Justificatifs", title: "Impression de reçus", subtitle: "Émet un reçu traçable pour chaque dépôt et chaque remise." },
  signatures: { eyebrow: "Chaîne de garde", title: "Signature électronique", subtitle: "Scelle la remise avec identité, heure, quantités et empreinte d’intégrité." },
  history: { eyebrow: "Traçabilité", title: "Historique complet", subtitle: "Retrouve chaque scan, contrôle, rangement, remise et synchronisation." },
  incidents: { eyebrow: "Traitement", title: "Incidents", subtitle: "Documente et escalade les événements qui affectent colis, personnes ou capacité." },
  anomalies: { eyebrow: "Contrôle Yobalelma", title: "Points à vérifier", subtitle: "Repère automatiquement retard, oubli, écart de mesure et mauvais emplacement." },
  refused: { eyebrow: "Non-conformité", title: "Colis refusés", subtitle: "Conserve le motif, les preuves et la décision pour les colis non acceptés." },
  pending: { eyebrow: "Priorités", title: "Colis en attente", subtitle: "Classe les colis à contrôler, ranger ou remettre avant leur échéance." },
  notifications: { eyebrow: "Centre d’alertes", title: "Notifications", subtitle: "Priorise les actions selon leur urgence et leur impact opérationnel." },
  offline: { eyebrow: "Continuité", title: "Mode hors ligne", subtitle: "Réception, contrôle et remise restent disponibles sans réseau puis sont rejoués sans doublon." },
  sync: { eyebrow: "Résilience", title: "Synchronisation automatique", subtitle: "Suit la file locale, les conflits et la dernière réplication sécurisée." },
  support: { eyebrow: "Assistance 24/7", title: "Support", subtitle: "Contacte les opérations, la sécurité ou le support matériel depuis le contexte du colis." },
  profile: { eyebrow: "Identité professionnelle", title: "Profil agent", subtitle: "Gère le point relais, les habilitations, langues et préférences locales." },
  settings: { eyebrow: "Configuration", title: "Paramètres", subtitle: "Configure langue, thème, unités, notifications, imprimantes et appareils autorisés." },
};

const statusTone: Record<RelayPackage["status"], Tone> = { expected: "info", received: "warning", controlled: "success", stored: "success", awaiting_carrier: "info", awaiting_recipient: "warning", handed_over: "success", refused: "danger", anomaly: "danger" };

export function RelayRoutePage({ segments, session, state }: { segments?: string[]; session: RelaySession; state: RelayState }) {
  const key = segments?.[0] ?? "dashboard";
  if (key === "dashboard") return <Dashboard state={state} />;
  if (key === "reception" || key === "scanner") return <Reception state={state} scanner={key === "scanner"} />;
  if (["quality","weighing","dimensions","photos"].includes(key)) return <QualityControl state={state} mode={key} />;
  if (key === "inventory" || key === "storage" || key === "locations") return <Inventory state={state} mode={key} />;
  if (key === "carrier-handover") return <Handover state={state} recipient={false} />;
  if (key === "recipient-handover" || key === "otp") return <Handover state={state} recipient />;
  if (key === "search") return <SearchPage state={state} />;
  return <ModulePage moduleKey={key} session={session} state={state} />;
}

function QualityControl({ state, mode }: { state: RelayState; mode: string }) {
  const router=useRouter(); const [trackingCode,setTrackingCode]=useState(state.packages[0]?.trackingCode??""); const selected=state.packages.find((item)=>item.trackingCode===trackingCode); const [weightKg,setWeightKg]=useState(selected?.weightKg??1); const [lengthCm,setLengthCm]=useState(selected?.dimensions.lengthCm??30); const [widthCm,setWidthCm]=useState(selected?.dimensions.widthCm??20); const [heightCm,setHeightCm]=useState(selected?.dimensions.heightCm??15); const [qualityScore,setQualityScore]=useState(selected?.qualityScore??100); const [photoCount,setPhotoCount]=useState(selected?.photoCount??0); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!trackingCode){setMessage("Sélectionnez un colis à contrôler.");return}setPending(true);setMessage("");try{const response=await fetch("/api/relay/controls",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingCode,relayPointId:state.relayPoint.id,idempotencyKey:`control:${trackingCode}:${Date.now()}`,weightKg,dimensions:{lengthCm,widthCm,heightCm},qualityScore,photoCount})});const body=await response.json() as {error?:string;decision?:string};if(!response.ok)throw new Error(body.error);const decision=body.decision==="refused"?"Colis refusé et isolé.":body.decision==="anomaly"?"Contrôle enregistré ; vérification complémentaire demandée.":"Contrôle validé et enregistré.";setMessage(decision);router.refresh()}catch(error){setMessage(error instanceof Error&&error.message?error.message:"Le contrôle n’a pas pu être enregistré.")}finally{setPending(false)}};
  const copy=labels[mode]??labels.quality;
  return <div className="grid gap-5"><PageHeader eyebrow={copy.eyebrow} title={copy.title} subtitle={copy.subtitle} actions={<Badge tone="success">Contrôle guidé</Badge>}/><div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><Panel title="Mesures et conformité"><form className="grid gap-3" onSubmit={submit}><label className="grid gap-1 text-sm font-black">Colis<select aria-label="Colis à contrôler" className={inputClass} value={trackingCode} onChange={(event)=>setTrackingCode(event.target.value)}><option value="">Sélectionner</option>{state.packages.map((item)=><option key={item.id} value={item.trackingCode}>{item.trackingCode}</option>)}</select></label><label className="grid gap-1 text-sm font-black">Poids mesuré (kg)<input aria-label="Poids mesuré" className={inputClass} type="number" min="0.1" max="300" step="0.1" value={weightKg} onChange={(event)=>setWeightKg(Number(event.target.value))}/></label><div className="grid grid-cols-3 gap-2"><NumberField label="Longueur" value={lengthCm} setValue={setLengthCm}/><NumberField label="Largeur" value={widthCm} setValue={setWidthCm}/><NumberField label="Hauteur" value={heightCm} setValue={setHeightCm}/></div><label className="grid gap-1 text-sm font-black">Conformité sur 100<input aria-label="Conformité" className={inputClass} type="number" min="0" max="100" value={qualityScore} onChange={(event)=>setQualityScore(Number(event.target.value))}/></label><label className="grid gap-1 text-sm font-black">Photos justificatives<input aria-label="Photos justificatives" className={inputClass} type="number" min="0" max="20" value={photoCount} onChange={(event)=>setPhotoCount(Number(event.target.value))}/></label><button disabled={pending||!state.relayPoint.id} className="h-11 rounded-lg bg-primary font-black text-white disabled:opacity-60">{pending?"Enregistrement…":"Valider le contrôle"}</button>{message?<p role="status" className={`rounded-lg p-3 text-sm font-bold ${message.includes("validé")?"bg-success/10 text-success":"bg-warning/10"}`}>{message}</p>:null}</form></Panel><Panel title="Colis à contrôler"><PackageTable packages={state.packages.filter((item)=>["received","controlled","anomaly"].includes(item.status))}/></Panel></div></div>;
}

function NumberField({label,value,setValue}:{label:string;value:number;setValue:(value:number)=>void}) { return <label className="grid gap-1 text-xs font-black">{label} (cm)<input aria-label={`${label} en centimètres`} className={inputClass} type="number" min="1" max="300" value={value} onChange={(event)=>setValue(Number(event.target.value))}/></label> }

function Dashboard({ state }: { state: RelayState }) {
  const capacity = forecastCapacity(state); const anomalies = detectRelayAnomalies(state); const pending = state.packages.filter((item) => ["expected", "received", "controlled"].includes(item.status)).length;
  return <div className="grid gap-5"><PageHeader eyebrow={`${state.relayPoint.network} · ${state.relayPoint.code}`} title={state.relayPoint.name} subtitle={anomalies.length?`${anomalies.length} point${anomalies.length>1?"s":""} demande${anomalies.length>1?"nt":""} votre attention.`:"Réception, rangement et remises sont à jour."} actions={<><ActionLink href="/relay/reception">Réceptionner</ActionLink><ActionLink href="/relay/scanner" secondary>Scanner</ActionLink></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Colis présents" value={String(state.packages.filter((p)=>!["expected","handed_over","refused"].includes(p.status)).length)} detail="inventaire actualisé" tone="success"/><Metric label="À traiter" value={String(pending)} detail="réceptions et contrôles" tone="warning"/><Metric label="Occupation" value={`${capacity.utilization}%`} detail={`${capacity.remaining} places disponibles`}/><Metric label="Points à vérifier" value={String(anomalies.length)} detail={anomalies.length?"action recommandée":"aucune action"} tone={anomalies.length?"danger":"success"}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Flux du jour"><div className="grid gap-3 sm:grid-cols-3"><Flow icon={PackageCheck} value={String(state.packages.filter((p)=>p.status==="received").length)} label="réceptionnés"/><Flow icon={Warehouse} value={String(state.packages.filter((p)=>p.status==="stored").length)} label="rangés"/><Flow icon={Boxes} value={String(state.packages.filter((p)=>p.status==="handed_over").length)} label="remis"/></div><div className="mt-4"><PackageTable packages={state.packages.slice(0,6)}/></div></Panel><Panel title="Aide à la décision"><div className="rounded-xl bg-black p-4 text-white"><div className="flex items-center gap-2 text-primary"><Sparkles className="h-5 w-5"/><p className="font-black">Capacité maîtrisée</p></div><p className="mt-2 text-sm text-white/70">Occupation prévue à {capacity.projectedUtilization} %. Consultez la carte des emplacements avant chaque rangement.</p></div><div className="mt-3 grid gap-2">{anomalies.slice(0,3).map((a)=><div className="rounded-lg border p-3" key={`${a.trackingCode}-${a.type}`}><p className="text-sm font-black">{a.message}</p><p className="mt-1 text-xs text-muted-foreground">{a.trackingCode}</p></div>)}{anomalies.length===0?<p className="py-4 text-center text-sm text-muted-foreground">Aucun point à vérifier.</p>:null}</div></Panel></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Emplacements sous surveillance"><LocationGrid locations={state.locations}/></Panel><Panel title="Journal récent"><EventList state={state}/></Panel></div></div>;
}

function Reception({ state, scanner }: { state: RelayState; scanner: boolean }) {
  const router=useRouter(); const [code,setCode]=useState(""); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false); const selected=state.packages.find((item)=>item.trackingCode===code.trim().toUpperCase()) ?? state.packages[0]; const recommendation=selected?suggestBestLocation(selected,state.locations):undefined;
  const submit=async(event:React.FormEvent)=>{event.preventDefault();const normalized=code.trim().toUpperCase();if(!/^YBL-[A-Z]{2}-\d{4}-\d{4}$/u.test(normalized)){setMessage("Référence non reconnue. Vérifiez le QR ou le code-barres.");return;}if(!state.relayPoint.id){setMessage("Votre point relais n’est pas encore associé à ce profil.");return;}setPending(true);setMessage("");try{const response=await fetch("/api/relay/movements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingCode:normalized,action:"check_in",relayPointId:state.relayPoint.id,idempotencyKey:`reception:${normalized}:${Date.now()}`})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error);setMessage(`${normalized} est réceptionné. Le contrôle du colis peut commencer${recommendation?.location.code?` ; emplacement conseillé : ${recommendation.location.code}`:""}.`);setCode("");router.refresh()}catch(error){setMessage(error instanceof Error&&error.message?error.message:"La réception n’a pas pu être enregistrée.")}finally{setPending(false)}};
  return <div className="grid gap-5"><PageHeader eyebrow="Entrée au point relais" title={scanner?"Scan QR & code-barres":"Réception colis"} subtitle="Contrôle identité, destination, doublon, poids et état avant toute entrée en inventaire." actions={<Badge tone="success"><ShieldCheck className="mr-1 h-4 w-4"/>Traçabilité active</Badge>}/><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Scanner ou saisir"><div className="grid place-items-center rounded-xl border border-dashed bg-muted/40 p-8"><span className="grid h-20 w-20 place-items-center rounded-2xl bg-black text-primary"><ScanLine className="h-10 w-10"/></span><p className="mt-4 font-black">Caméra prête</p><p className="text-sm text-muted-foreground">QR ou code-barres Yobalelma</p></div><form className="mt-4 grid gap-3" onSubmit={submit}><input aria-label="Code du colis" className={inputClass} placeholder="YBL-SN-2607-0202" value={code} onChange={(event)=>setCode(event.target.value)}/><button disabled={pending} className="h-11 rounded-lg bg-primary font-black text-white disabled:opacity-60">{pending?"Enregistrement…":"Valider la réception"}</button></form>{message?<p role="status" className={`mt-3 rounded-lg p-3 text-sm font-bold ${message.includes("est réceptionné")?"bg-success/10 text-success":"bg-error/10 text-error"}`}>{message}</p>:null}</Panel><Panel title="File de réception"><PackageTable packages={state.packages.filter((p)=>["expected","received","controlled"].includes(p.status))}/></Panel></div></div>;
}

function Inventory({ state, mode }: { state: RelayState; mode: string }) {
  const stored=state.packages.filter((p)=>p.locationCode); const unassigned=state.packages.filter((p)=>!["expected","handed_over","refused"].includes(p.status)&&!p.locationCode); return <div className="grid gap-5"><PageHeader eyebrow="Inventaire physique et suivi" title={mode==="inventory"?"Inventaire":mode==="storage"?"Rangement guidé":"Emplacements de stockage"} subtitle="Chaque colis est associé à une position vérifiée et à une capacité compatible." actions={<ActionLink href="/relay/scanner">Scanner un emplacement</ActionLink>}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Colis localisés" value={String(stored.length)} detail="positions confirmées" tone="success"/><Metric label="Emplacements" value={String(state.locations.length)} detail="toutes zones"/><Metric label="À affecter" value={String(unassigned.length)} detail="rangement requis" tone={unassigned.length?"warning":"success"}/></div>{mode==="storage"?<StorageAssignment state={state} packages={unassigned}/>:null}<div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><Panel title="Carte de capacité"><LocationGrid locations={state.locations}/></Panel><Panel title="Inventaire"><PackageTable packages={state.packages.filter((p)=>!["expected","handed_over"].includes(p.status))}/></Panel></div></div>;
}

function StorageAssignment({state,packages}:{state:RelayState;packages:RelayPackage[]}) { const router=useRouter(); const [trackingCode,setTrackingCode]=useState(packages[0]?.trackingCode??""); const [locationId,setLocationId]=useState(state.locations.find((item)=>item.status==="available")?.id??""); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false); const submit=async(event:React.FormEvent)=>{event.preventDefault();setPending(true);setMessage("");try{const response=await fetch("/api/relay/storage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingCode,relayPointId:state.relayPoint.id,locationId})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error);setMessage("Emplacement confirmé et inventaire actualisé.");router.refresh()}catch(error){setMessage(error instanceof Error&&error.message?error.message:"Le rangement n’a pas pu être enregistré.")}finally{setPending(false)}}; return <Panel title="Affecter un emplacement"><form className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end" onSubmit={submit}><label className="grid gap-1 text-sm font-black">Colis<select aria-label="Colis à ranger" className={inputClass} value={trackingCode} onChange={(event)=>setTrackingCode(event.target.value)}><option value="">Sélectionner</option>{packages.map((item)=><option key={item.id} value={item.trackingCode}>{item.trackingCode}</option>)}</select></label><label className="grid gap-1 text-sm font-black">Emplacement<select aria-label="Emplacement choisi" className={inputClass} value={locationId} onChange={(event)=>setLocationId(event.target.value)}><option value="">Sélectionner</option>{state.locations.filter((item)=>item.status!=="full"&&item.status!=="maintenance").map((item)=><option key={item.id} value={item.id}>{item.code} — {locationKindLabel[item.kind]}</option>)}</select></label><button disabled={pending||!trackingCode||!locationId} className="h-11 rounded-lg bg-primary px-5 font-black text-white disabled:opacity-60">{pending?"Enregistrement…":"Confirmer"}</button></form>{message?<p role="status" className={`mt-3 rounded-lg p-3 text-sm font-bold ${message.startsWith("Emplacement confirmé")?"bg-success/10 text-success":"bg-error/10 text-error"}`}>{message}</p>:null}</Panel> }

function Handover({ state, recipient }: { state: RelayState; recipient: boolean }) {
  const router=useRouter(); const [otp,setOtp]=useState(""); const [signerName,setSignerName]=useState(""); const [trackingCode,setTrackingCode]=useState(""); const [status,setStatus]=useState(""); const [pending,setPending]=useState(false); const items=state.packages.filter((p)=>p.status===(recipient?"awaiting_recipient":"awaiting_carrier")); const selected=items.find((item)=>item.trackingCode===trackingCode)||items[0];
  const verify=async(event:React.FormEvent)=>{event.preventDefault();if(!selected){setStatus("Aucun colis n’est prêt pour cette remise.");return}if(recipient&&!/^\d{6}$/u.test(otp)){setStatus("Le code de sécurité doit contenir 6 chiffres.");return}if(signerName.trim().length<2){setStatus("Indiquez le nom de la personne qui reçoit le colis.");return}setPending(true);setStatus("");try{const response=await fetch("/api/relay/handovers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingCode:selected.trackingCode,shipmentId:selected.id,relayPointId:state.relayPoint.id,recipientType:recipient?"recipient":"internal_carrier",otpCode:recipient?otp:undefined,signerName,idempotencyKey:`handover:${selected.id}:${Date.now()}`})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error);setStatus("Remise confirmée et justificatif enregistré.");setOtp("");setSignerName("");router.refresh()}catch(error){setStatus(error instanceof Error&&error.message?error.message:"La remise n’a pas pu être enregistrée.")}finally{setPending(false)}};
  return <div className="grid gap-5"><PageHeader eyebrow="Transfert de responsabilité" title={recipient?"Remise au destinataire":"Remise au transporteur interne"} subtitle={recipient?"Vérifiez l’identité, le code à usage unique et la confirmation avant la sortie du colis.":"Contrôlez le manifeste, les quantités, le véhicule et l’identité du transporteur."} actions={<Badge tone="success">{items.length} colis prêts</Badge>}/><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title={recipient?"Colis à retirer":"Manifeste de collecte"}><PackageTable packages={items}/></Panel><Panel title={recipient?"Confirmation sécurisée":"Validation transporteur"}><form className="grid gap-3" onSubmit={verify}><label className="text-sm font-black" htmlFor="shipment">Colis à remettre</label><select id="shipment" aria-label="Colis à remettre" className={inputClass} value={selected?.trackingCode??""} onChange={(event)=>setTrackingCode(event.target.value)} disabled={items.length===0}>{items.length?<>{items.map((item)=><option key={item.id} value={item.trackingCode}>{item.trackingCode} — {item.recipient}</option>)}</>:<option value="">Aucun colis prêt</option>}</select><label className="text-sm font-black" htmlFor="signer">{recipient?"Nom du destinataire":"Nom du transporteur"}</label><input id="signer" aria-label={recipient?"Nom du destinataire":"Nom du transporteur"} className={inputClass} value={signerName} onChange={(event)=>setSignerName(event.target.value)}/>{recipient?<><label className="text-sm font-black" htmlFor="otp">Code à 6 chiffres</label><input id="otp" aria-label="Code de sécurité" inputMode="numeric" maxLength={6} className={inputClass} placeholder="000000" value={otp} onChange={(e)=>setOtp(e.target.value.replace(/\D/gu,""))}/></>:null}<button disabled={pending||items.length===0} className="h-11 rounded-lg bg-primary font-black text-white disabled:opacity-60">{recipient?<><KeyRound className="mr-2 inline h-4 w-4"/>{pending?"Vérification…":"Confirmer la remise"}</>:pending?"Enregistrement…":"Signer la remise"}</button>{status?<p role="status" className={`rounded-lg p-3 text-sm font-bold ${status.startsWith("Remise confirmée")?"bg-success/10 text-success":"bg-error/10 text-error"}`}>{status}</p>:null}</form></Panel></div></div>;
}

function SearchPage({ state }: { state: RelayState }) { const [query,setQuery]=useState(""); const results=useMemo(()=>state.packages.filter((p)=>`${p.trackingCode} ${p.recipient} ${p.locationCode}`.toLowerCase().includes(query.toLowerCase())),[query,state]); return <div className="grid gap-5"><PageHeader eyebrow="Recherche globale" title="Retrouver un colis" subtitle="Recherche par référence, destinataire, lot ou emplacement."/><Panel><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input aria-label="Rechercher un colis" className={`${inputClass} w-full pl-10`} value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Référence, destinataire ou A-01"/></div><div className="mt-5"><PackageTable packages={results}/></div></Panel></div>; }

function ModulePage({ moduleKey, session, state }: { moduleKey:string; session:RelaySession; state:RelayState }) {
  const copy=labels[moduleKey]??{eyebrow:"Opérations Yobalelma",title:"Opération point relais",subtitle:"Module sécurisé, synchronisé et entièrement traçable."}; const anomalies=detectRelayAnomalies(state); const printModule=moduleKey==="labels"||moduleKey==="receipts"; const rows=moduleKey==="history"?state.events.map((e)=>({title:eventActionLabel[e.action]??"Opération enregistrée",detail:`${e.entity} · ${e.detail}`})):moduleKey==="notifications"?state.notifications.map((n)=>({title:n.title,detail:n.message})):moduleKey==="incidents"?state.incidents.map((i)=>({title:i.title,detail:`Priorité ${incidentSeverityLabel[i.severity]} · ${incidentStatusLabel[i.status]}`})):moduleKey==="anomalies"?anomalies.map((a)=>({title:a.message,detail:a.trackingCode})):state.packages.slice(0,6).map((p)=>({title:p.trackingCode,detail:`${p.recipient} · ${p.locationCode??"à affecter"}`}));
  return <div className="grid gap-5"><PageHeader eyebrow={copy.eyebrow} title={copy.title} subtitle={copy.subtitle} actions={<Badge tone="success">{relayRoleLabel[session.role]}</Badge>}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="État" value="Opérationnel" detail="contrôles actifs" tone="success"/><Metric label="Éléments" value={String(rows.length)} detail="dans la vue"/><Metric label="Traçabilité" value="Active" detail="actions enregistrées"/></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Vue opérationnelle"><div className="grid gap-3">{rows.map((r,i)=><div className="flex items-start gap-3 rounded-lg border p-3" key={`${r.title}-${i}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-black text-primary">{printModule?<Printer className="h-5 w-5"/>:moduleKey==="photos"?<Camera className="h-5 w-5"/>:moduleKey==="incidents"?<AlertTriangle className="h-5 w-5"/>:<Archive className="h-5 w-5"/>}</span><div><p className="font-black">{r.title}</p><p className="text-sm text-muted-foreground">{r.detail}</p></div></div>)}{rows.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Aucun élément ne demande votre attention pour le moment.</p>:null}</div></Panel><Panel title="Actions"><div className="rounded-xl bg-black p-4 text-white"><p className="font-black text-primary">Contrôle Yobalelma actif</p><p className="mt-2 text-sm text-white/70">Les droits d’accès et les règles opérationnelles sont vérifiés à chaque action.</p></div><button type="button" onClick={()=>window.location.reload()} className="mt-4 h-11 w-full rounded-lg bg-primary font-black text-white">{printModule?"Imprimer un exemplaire":moduleKey==="photos"?"Ajouter une photo":"Actualiser la vue"}</button></Panel></div></div>;
}

function PackageTable({ packages }: { packages:RelayPackage[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2">Référence</th><th>Destinataire</th><th>Poids</th><th>Emplacement</th><th>État</th></tr></thead><tbody>{packages.map((p)=><tr className="border-t" key={p.id}><td className="p-2 font-black">{p.trackingCode}</td><td>{p.recipient}</td><td>{p.weightKg.toFixed(1)} kg</td><td>{p.locationCode??"À affecter"}</td><td><Badge tone={statusTone[p.status]}>{packageStatusLabel[p.status]}</Badge></td></tr>)}</tbody></table>{packages.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Aucun colis ne correspond à cette vue.</p>:null}</div>; }
function LocationGrid({ locations }: { locations:RelayState["locations"] }) { return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{locations.map((l)=><div className="rounded-lg border p-3" key={l.id}><div className="flex items-center justify-between"><p className="font-black">{l.code}</p><Badge tone={l.status==="full"?"danger":l.status==="near_capacity"?"warning":"success"}>{locationUtilization(l)}%</Badge></div><p className="mt-1 text-xs text-muted-foreground">{l.zone} · {locationKindLabel[l.kind]}</p><div className="mt-3 h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary" style={{width:`${locationUtilization(l)}%`}}/></div></div>)}{locations.length===0?<p className="col-span-full py-8 text-center text-sm text-muted-foreground">Aucun emplacement n’est encore configuré pour ce point relais.</p>:null}</div>; }
function Flow({ icon:Icon,value,label }:{icon:typeof Boxes;value:string;label:string}){return <div className="flex items-center gap-3 rounded-xl bg-muted p-4"><Icon className="h-7 w-7 text-primary"/><div><p className="text-2xl font-black">{value}</p><p className="text-xs font-bold text-muted-foreground">{label}</p></div></div>}
function EventList({state}:{state:RelayState}){return <div className="grid gap-3">{state.events.map((e)=><div className="border-l-2 border-primary pl-3" key={e.id}><p className="text-sm font-black">{eventActionLabel[e.action]??"Opération enregistrée"}</p><p className="text-xs text-muted-foreground">{e.entity} · {e.detail}</p></div>)}{state.events.length===0?<p className="py-6 text-center text-sm text-muted-foreground">Aucune opération récente.</p>:null}</div>}
