"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Archive, Boxes, Camera, CheckCircle2, KeyRound, PackageCheck, Printer, ScanLine, Search, ShieldCheck, Sparkles, Warehouse } from "lucide-react";
import { detectRelayAnomalies, forecastCapacity, locationUtilization, suggestBestLocation } from "../lib/optimizer";
import type { RelayPackage, RelaySession, RelayState, Tone } from "../lib/types";
import { ActionLink, Badge, inputClass, Metric, PageHeader, Panel } from "./relay-ui";

const labels: Record<string, { eyebrow: string; title: string; subtitle: string }> = {
  quality: { eyebrow: "Contrôle contradictoire", title: "Contrôle qualité", subtitle: "Poids, dimensions, emballage, photos et conformité sont vérifiés avant stockage." },
  weighing: { eyebrow: "Métrologie", title: "Pesée des colis", subtitle: "Compare la mesure certifiée au poids déclaré et bloque les écarts hors tolérance." },
  dimensions: { eyebrow: "Gabarit", title: "Vérification des dimensions", subtitle: "Mesure longueur, largeur et hauteur pour sécuriser la facturation et le rangement." },
  photos: { eyebrow: "Preuves", title: "Photos des colis", subtitle: "Conserve les preuves horodatées du colis, de l’étiquette et des éventuelles avaries." },
  shelves: { eyebrow: "Organisation", title: "Gestion des rayonnages", subtitle: "Visualise charge, poids admissible et occupation de chaque rayonnage." },
  lockers: { eyebrow: "Retraits sécurisés", title: "Gestion des casiers", subtitle: "Pilote les casiers OTP et leur disponibilité en temps réel." },
  labels: { eyebrow: "Étiquetage", title: "Impression d’étiquettes", subtitle: "Produit des étiquettes QR et code-barres conformes au réseau Yobalelma." },
  receipts: { eyebrow: "Justificatifs", title: "Impression de reçus", subtitle: "Émet un reçu traçable pour chaque dépôt et chaque remise." },
  signatures: { eyebrow: "Chaîne de garde", title: "Signature électronique", subtitle: "Scelle la remise avec identité, heure, quantités et empreinte d’intégrité." },
  history: { eyebrow: "Audit", title: "Historique complet", subtitle: "Retrouve chaque scan, contrôle, rangement, remise et synchronisation." },
  incidents: { eyebrow: "Traitement", title: "Incidents", subtitle: "Documente et escalade les événements qui affectent colis, personnes ou capacité." },
  anomalies: { eyebrow: "Yobalelma Intelligence", title: "Anomalies détectées", subtitle: "Repère automatiquement retard, oubli, écart de mesure et mauvais emplacement." },
  refused: { eyebrow: "Non-conformité", title: "Colis refusés", subtitle: "Conserve le motif, les preuves et la décision pour les colis non acceptés." },
  pending: { eyebrow: "Priorités", title: "Colis en attente", subtitle: "Classe les colis à contrôler, ranger ou remettre avant leur échéance." },
  notifications: { eyebrow: "Centre d’alertes", title: "Notifications", subtitle: "Priorise les actions selon leur urgence et leur impact opérationnel." },
  offline: { eyebrow: "Continuité", title: "Mode hors ligne", subtitle: "Réception, contrôle et remise restent disponibles sans réseau puis sont rejoués sans doublon." },
  sync: { eyebrow: "Résilience", title: "Synchronisation automatique", subtitle: "Suit la file locale, les conflits et la dernière réplication sécurisée." },
  support: { eyebrow: "Assistance 24/7", title: "Support", subtitle: "Contacte les opérations, la sécurité ou le support matériel depuis le contexte du colis." },
  profile: { eyebrow: "Identité professionnelle", title: "Profil agent", subtitle: "Gère le point relais, les habilitations, langues et préférences locales." },
  settings: { eyebrow: "Configuration", title: "Paramètres", subtitle: "Configure langue, thème, unités, notifications, imprimantes et appareils autorisés." },
};

const statusTone: Record<RelayPackage["status"], Tone> = { expected: "info", received: "warning", controlled: "success", stored: "success", awaiting_carrier: "info", awaiting_recipient: "warning", handed_over: "success", refused: "danger", anomaly: "danger" };

export function RelayRoutePage({ segments, session, state }: { segments?: string[]; session: RelaySession; state: RelayState }) {
  const key = segments?.[0] ?? "dashboard";
  if (key === "dashboard") return <Dashboard state={state} />;
  if (key === "reception" || key === "scanner") return <Reception state={state} scanner={key === "scanner"} />;
  if (key === "inventory" || key === "storage" || key === "locations") return <Inventory state={state} mode={key} />;
  if (key === "carrier-handover") return <Handover state={state} recipient={false} />;
  if (key === "recipient-handover" || key === "otp") return <Handover state={state} recipient />;
  if (key === "search") return <SearchPage state={state} />;
  return <ModulePage moduleKey={key} session={session} state={state} />;
}

function Dashboard({ state }: { state: RelayState }) {
  const capacity = forecastCapacity(state); const anomalies = detectRelayAnomalies(state); const pending = state.packages.filter((item) => ["expected", "received", "controlled"].includes(item.status)).length;
  return <div className="grid gap-5"><PageHeader eyebrow={`${state.relayPoint.network} · ${state.relayPoint.code}`} title="Point Relais Plateau" subtitle="Réception, stockage et remises sont synchronisés. Deux actions prioritaires demandent votre contrôle." actions={<><ActionLink href="/relay/reception">Réceptionner</ActionLink><ActionLink href="/relay/scanner" secondary>Scanner</ActionLink></>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Colis présents" value={String(state.packages.filter((p)=>!["expected","handed_over","refused"].includes(p.status)).length)} detail="inventaire temps réel" tone="success"/><Metric label="À traiter" value={String(pending)} detail="réceptions et contrôles" tone="warning"/><Metric label="Occupation" value={`${capacity.utilization}%`} detail={`${capacity.remaining} places projetées`}/><Metric label="Alertes IA" value={String(anomalies.length)} detail="1 action bloquante" tone="danger"/></div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Flux du jour"><div className="grid gap-3 sm:grid-cols-3"><Flow icon={PackageCheck} value="18" label="réceptionnés"/><Flow icon={Warehouse} value="12" label="rangés"/><Flow icon={Boxes} value="9" label="remis"/></div><div className="mt-4"><PackageTable packages={state.packages.slice(0,6)}/></div></Panel><Panel title="Yobalelma Intelligence"><div className="rounded-xl bg-black p-4 text-white"><div className="flex items-center gap-2 text-primary"><Sparkles className="h-5 w-5"/><p className="font-black">Capacité maîtrisée</p></div><p className="mt-2 text-sm text-white/70">Occupation projetée à {capacity.projectedUtilization}%. Dirigez les retraits vers C-02 et réservez X-01 aux hors-gabarit.</p></div><div className="mt-3 grid gap-2">{anomalies.slice(0,3).map((a)=><div className="rounded-lg border p-3" key={`${a.trackingCode}-${a.type}`}><p className="text-sm font-black">{a.message}</p><p className="mt-1 text-xs text-muted-foreground">{a.trackingCode}</p></div>)}</div></Panel></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Emplacements sous surveillance"><LocationGrid locations={state.locations}/></Panel><Panel title="Journal récent"><EventList state={state}/></Panel></div></div>;
}

function Reception({ state, scanner }: { state: RelayState; scanner: boolean }) {
  const [code,setCode]=useState(""); const [message,setMessage]=useState(""); const selected=state.packages.find((item)=>item.trackingCode===code.trim().toUpperCase()) ?? state.packages[1]; const recommendation=suggestBestLocation(selected,state.locations);
  const submit=(event:React.FormEvent)=>{event.preventDefault();const normalized=code.trim().toUpperCase();if(!/^YBL-[A-Z]{2}-\d{4}-\d{4}$/u.test(normalized)){setMessage("Code non reconnu. Vérifiez le QR ou le code-barres.");return;}setMessage(`${normalized} réceptionné. Contrôle qualité ouvert et emplacement ${recommendation?.location.code ?? "sécurisé"} réservé.`);setCode("");};
  return <div className="grid gap-5"><PageHeader eyebrow="Entrée au point relais" title={scanner?"Scan QR & code-barres":"Réception colis"} subtitle="Contrôle identité, destination, doublon, poids et état avant toute entrée en inventaire." actions={<Badge tone="success"><ShieldCheck className="mr-1 h-4 w-4"/>Traçabilité active</Badge>}/><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Panel title="Scanner ou saisir"><div className="grid place-items-center rounded-xl border border-dashed bg-muted/40 p-8"><span className="grid h-20 w-20 place-items-center rounded-2xl bg-black text-primary"><ScanLine className="h-10 w-10"/></span><p className="mt-4 font-black">Caméra prête</p><p className="text-sm text-muted-foreground">QR ou code-barres Yobalelma</p></div><form className="mt-4 grid gap-3" onSubmit={submit}><input aria-label="Code du colis" className={inputClass} placeholder="YBL-SN-2607-0202" value={code} onChange={(event)=>setCode(event.target.value)}/><button className="h-11 rounded-lg bg-primary font-black text-white">Valider la réception</button></form>{message?<p role="status" className={`mt-3 rounded-lg p-3 text-sm font-bold ${message.includes("non reconnu")?"bg-error/10 text-error":"bg-success/10 text-success"}`}>{message}</p>:null}</Panel><Panel title="File de réception"><PackageTable packages={state.packages.filter((p)=>["expected","received","controlled"].includes(p.status))}/></Panel></div></div>;
}

function Inventory({ state, mode }: { state: RelayState; mode: string }) {
  const stored=state.packages.filter((p)=>p.locationCode); return <div className="grid gap-5"><PageHeader eyebrow="Inventaire physique & numérique" title={mode==="inventory"?"Inventaire":mode==="storage"?"Stockage intelligent":"Emplacements de stockage"} subtitle="Chaque colis est associé à une position vérifiée et à une capacité compatible." actions={<ActionLink href="/relay/scanner">Scanner un emplacement</ActionLink>}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Colis localisés" value={String(stored.length)} detail="positions confirmées" tone="success"/><Metric label="Emplacements" value={String(state.locations.length)} detail="toutes zones"/><Metric label="À vérifier" value="1" detail="écart de rangement" tone="warning"/></div><div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><Panel title="Carte de capacité"><LocationGrid locations={state.locations}/></Panel><Panel title="Inventaire"><PackageTable packages={state.packages.filter((p)=>!["expected","handed_over"].includes(p.status))}/></Panel></div></div>;
}

function Handover({ state, recipient }: { state: RelayState; recipient: boolean }) {
  const [otp,setOtp]=useState(""); const [status,setStatus]=useState(""); const items=state.packages.filter((p)=>p.status===(recipient?"awaiting_recipient":"awaiting_carrier"));
  const verify=(event:React.FormEvent)=>{event.preventDefault();setStatus(/^\d{6}$/u.test(otp)?"OTP vérifié. Identité confirmée, signature et reçu prêts.":"Le code OTP doit contenir 6 chiffres.");};
  return <div className="grid gap-5"><PageHeader eyebrow="Transfert de responsabilité" title={recipient?"Remise au destinataire":"Remise au transporteur interne"} subtitle={recipient?"Vérifie l’identité, l’OTP à usage unique et la signature avant sortie.":"Contrôle le manifeste, les quantités, le véhicule et la signature du transporteur."} actions={<Badge tone="success">{items.length} colis prêts</Badge>}/><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title={recipient?"Colis à retirer":"Manifeste de collecte"}><PackageTable packages={items}/></Panel><Panel title={recipient?"Validation OTP":"Validation transporteur"}>{recipient?<form className="grid gap-3" onSubmit={verify}><label className="text-sm font-black" htmlFor="otp">Code à 6 chiffres</label><input id="otp" aria-label="Code OTP" inputMode="numeric" maxLength={6} className={inputClass} placeholder="000000" value={otp} onChange={(e)=>setOtp(e.target.value)}/><button className="h-11 rounded-lg bg-primary font-black text-white"><KeyRound className="mr-2 inline h-4 w-4"/>Vérifier l’OTP</button>{status?<p role="status" className={`rounded-lg p-3 text-sm font-bold ${status.startsWith("OTP")?"bg-success/10 text-success":"bg-error/10 text-error"}`}>{status}</p>:null}</form>:<div className="grid gap-3">{["Badge et mission vérifiés","Quantités conformes","Scellé disponible","Signature requise"].map((x)=><div className="flex items-center gap-2 rounded-lg border p-3 text-sm font-bold" key={x}><CheckCircle2 className="h-4 w-4 text-success"/>{x}</div>)}<button className="h-11 rounded-lg bg-primary font-black text-white">Signer la remise</button></div>}</Panel></div></div>;
}

function SearchPage({ state }: { state: RelayState }) { const [query,setQuery]=useState(""); const results=useMemo(()=>state.packages.filter((p)=>`${p.trackingCode} ${p.recipient} ${p.locationCode}`.toLowerCase().includes(query.toLowerCase())),[query,state]); return <div className="grid gap-5"><PageHeader eyebrow="Recherche globale" title="Retrouver un colis" subtitle="Recherche par tracking, destinataire, lot ou emplacement."/><Panel><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input aria-label="Rechercher un colis" className={`${inputClass} w-full pl-10`} value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tracking, destinataire ou A-01"/></div><div className="mt-5"><PackageTable packages={results}/></div></Panel></div>; }

function ModulePage({ moduleKey, session, state }: { moduleKey:string; session:RelaySession; state:RelayState }) {
  const copy=labels[moduleKey]??{eyebrow:"Relay App",title:"Opération point relais",subtitle:"Module sécurisé, synchronisé et entièrement traçable."}; const anomalies=detectRelayAnomalies(state); const printModule=moduleKey==="labels"||moduleKey==="receipts"; const rows=moduleKey==="history"?state.events.map((e)=>({title:e.action,detail:`${e.entity} · ${e.detail}`})):moduleKey==="notifications"?state.notifications.map((n)=>({title:n.title,detail:n.message})):moduleKey==="incidents"?state.incidents.map((i)=>({title:i.title,detail:`${i.severity} · ${i.status}`})):moduleKey==="anomalies"?anomalies.map((a)=>({title:a.message,detail:a.trackingCode})):state.packages.slice(0,6).map((p)=>({title:p.trackingCode,detail:`${p.recipient} · ${p.locationCode??"à affecter"}`}));
  return <div className="grid gap-5"><PageHeader eyebrow={copy.eyebrow} title={copy.title} subtitle={copy.subtitle} actions={<Badge tone="success">{session.role}</Badge>}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="État" value="Opérationnel" detail="contrôles actifs" tone="success"/><Metric label="Éléments" value={String(rows.length)} detail="dans la vue"/><Metric label="Audit" value="100%" detail="actions journalisées"/></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Vue opérationnelle"><div className="grid gap-3">{rows.map((r,i)=><div className="flex items-start gap-3 rounded-lg border p-3" key={`${r.title}-${i}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-black text-primary">{printModule?<Printer className="h-5 w-5"/>:moduleKey==="photos"?<Camera className="h-5 w-5"/>:moduleKey==="incidents"?<AlertTriangle className="h-5 w-5"/>:<Archive className="h-5 w-5"/>}</span><div><p className="font-black">{r.title}</p><p className="text-sm text-muted-foreground">{r.detail}</p></div></div>)}</div></Panel><Panel title="Actions"><div className="rounded-xl bg-black p-4 text-white"><p className="font-black text-primary">Contrôle automatique actif</p><p className="mt-2 text-sm text-white/70">Permissions, validation métier et journal d’audit sont appliqués à chaque opération.</p></div><button className="mt-4 h-11 w-full rounded-lg bg-primary font-black text-white">{printModule?"Imprimer un exemplaire":moduleKey==="photos"?"Ajouter une photo":"Actualiser les contrôles"}</button></Panel></div></div>;
}

function PackageTable({ packages }: { packages:RelayPackage[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2">Tracking</th><th>Destinataire</th><th>Poids</th><th>Emplacement</th><th>État</th></tr></thead><tbody>{packages.map((p)=><tr className="border-t" key={p.id}><td className="p-2 font-black">{p.trackingCode}</td><td>{p.recipient}</td><td>{p.weightKg.toFixed(1)} kg</td><td>{p.locationCode??"—"}</td><td><Badge tone={statusTone[p.status]}>{p.status}</Badge></td></tr>)}</tbody></table>{packages.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Aucun colis ne correspond à cette vue.</p>:null}</div>; }
function LocationGrid({ locations }: { locations:RelayState["locations"] }) { return <div className="grid grid-cols-2 gap-3">{locations.map((l)=><div className="rounded-lg border p-3" key={l.id}><div className="flex items-center justify-between"><p className="font-black">{l.code}</p><Badge tone={l.status==="full"?"danger":l.status==="near_capacity"?"warning":"success"}>{locationUtilization(l)}%</Badge></div><p className="mt-1 text-xs text-muted-foreground">{l.zone} · {l.kind}</p><div className="mt-3 h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary" style={{width:`${locationUtilization(l)}%`}}/></div></div>)}</div>; }
function Flow({ icon:Icon,value,label }:{icon:typeof Boxes;value:string;label:string}){return <div className="flex items-center gap-3 rounded-xl bg-muted p-4"><Icon className="h-7 w-7 text-primary"/><div><p className="text-2xl font-black">{value}</p><p className="text-xs font-bold text-muted-foreground">{label}</p></div></div>}
function EventList({state}:{state:RelayState}){return <div className="grid gap-3">{state.events.map((e)=><div className="border-l-2 border-primary pl-3" key={e.id}><p className="text-sm font-black">{e.action}</p><p className="text-xs text-muted-foreground">{e.entity} · {e.detail}</p></div>)}</div>}
