import {readFile} from "node:fs/promises";
import path from "node:path";
import {describe,expect,it} from "vitest";
import {calculateNetworkHealth,controlEventSchema,prioritizeAttention,type TowerKpis} from "@/lib/control-tower/core";
import {controlTowerModules,validateModuleGraph} from "@/lib/control-tower/modules";
import {generateOperationalRecommendations} from "@/lib/control-tower/recommendations";
import {buildReplayTimeline,replayStateAt} from "@/lib/control-tower/replay";

const healthy:TowerKpis={activeShipments:100,activeMissions:20,openIncidents:0,criticalAlerts:0,onlineDrivers:18,staleDrivers:0,hubCapacityPercent:55,paymentExceptions:0,customsBlocked:0,notificationBacklog:0};
describe("Global Operations Control Tower",()=>{
  it("keeps the requested modules independent with a valid dependency graph",()=>{expect(validateModuleGraph()).toBe(true);expect(controlTowerModules).toHaveLength(16);expect(controlTowerModules.find((item)=>item.id==="digital_twin")?.dependencies).toContain("core");});
  it("summarizes a nominal network in under ten signals",()=>expect(calculateNetworkHealth(healthy)).toEqual({score:100,status:"nominal",reasons:[]}));
  it("makes critical degradation explicit",()=>{const result=calculateNetworkHealth({...healthy,criticalAlerts:4,openIncidents:3,hubCapacityPercent:96});expect(result.status).toBe("critical");expect(result.reasons).toContain("Capacité Hub critique");});
  it("sorts attention by operational impact",()=>expect(prioritizeAttention({...healthy,criticalAlerts:2,openIncidents:5})[0]?.key).toBe("critical_alerts"));
  it("explains recommendations and requires human approval",()=>{const items=generateOperationalRecommendations({...healthy,hubCapacityPercent:96,staleDrivers:2});expect(items.length).toBe(2);expect(items.every((item)=>item.requiresHumanApproval)).toBe(true);expect(items[0].evidence.length).toBeGreaterThan(0);});
  it("never invents recommendations without a signal",()=>expect(generateOperationalRecommendations(healthy)).toEqual([]));
  it("removes non-operational and sensitive fields from event payloads",()=>{const event=controlEventSchema.parse({sourceModule:"payments",sourceEventId:"p1",eventType:"payment.updated",entityType:"shipment",entityId:"s1",countryCode:"SN",occurredAt:"2026-07-22T10:00:00Z",sanitizedPayload:{operational_status:"pending",token:"forbidden",otp:"forbidden"}});expect(event.sanitizedPayload).toEqual({operational_status:"pending"});});
  it("replays events deterministically",()=>{const base={sourceModule:"dispatch",eventType:"mission.updated",entityType:"mission",entityId:"m1",countryCode:"SN",severity:"info" as const,sanitizedPayload:{}};const events=[controlEventSchema.parse({...base,sourceEventId:"2",occurredAt:"2026-07-22T10:01:00Z"}),controlEventSchema.parse({...base,sourceEventId:"1",occurredAt:"2026-07-22T10:00:00Z"})];expect(buildReplayTimeline(events).map((item)=>item.sourceEventId)).toEqual(["1","2"]);expect(replayStateAt([{occurredAt:"2026-07-22T10:00:00Z",state:"a"},{occurredAt:"2026-07-22T11:00:00Z",state:"b"}],"2026-07-22T10:30:00Z")).toBe("a");});
  it("processes a high-volume replay without quadratic scans",()=>{const start=performance.now();const events=Array.from({length:50_000},(_,index)=>controlEventSchema.parse({sourceModule:"shipments",sourceEventId:String(50_000-index),eventType:"shipment.updated",entityType:"shipment",entityId:String(index),countryCode:"SN",occurredAt:new Date(1_750_000_000_000+index*1000).toISOString(),sanitizedPayload:{}}));expect(buildReplayTimeline(events)).toHaveLength(50_000);expect(performance.now()-start).toBeLessThan(5000);});
  it("uses an idempotent service-only outbox and an interactive real-coordinate map",async()=>{const sql=await readFile(path.resolve(process.cwd(),"supabase/migrations/20260722058000_global_operations_control_tower.sql"),"utf8");const map=await readFile(path.resolve(process.cwd(),"apps/admin-app/src/components/operational-map.tsx"),"utf8");expect(sql).toContain("unique(source_module,source_event_id)");expect(sql).toContain("for update skip locked");expect(sql).toContain("Service role required");expect(map).toContain("aucune position inventée");expect(map).toContain("regroupement spatial actif");expect(map).toContain("requestFullscreen");expect(map).toContain("sélection(s)");expect(map).toContain("position(s) ancienne(s)");});
  it("offers deterministic replay controls without generating history",async()=>{const timeline=await readFile(path.resolve(process.cwd(),"apps/admin-app/src/components/operational-timeline.tsx"),"utf8");expect(timeline).toContain("Timeline et replay déterministe");expect(timeline).toContain("Le replay ne fabrique aucun historique");expect(timeline).toContain("Vitesse du replay");});
  it("connects critical domains to the event bus and keeps the outbox client-closed",async()=>{const events=await readFile(path.resolve(process.cwd(),"supabase/migrations/20260722060000_control_tower_domain_events.sql"),"utf8");const policy=await readFile(path.resolve(process.cwd(),"supabase/migrations/20260722061000_control_tower_outbox_fail_closed.sql"),"utf8");for(const table of ["shipments","operational_incidents","driver_operational_states","payments","customs_cases","airport_hubs","relay_points","local_delivery_missions"])expect(events).toContain(`on public.${table}`);expect(policy).toContain("using (false) with check (false)");});
  it("has bounded retry and dead-letter resilience",async()=>{const worker=await readFile(path.resolve(process.cwd(),"supabase/migrations/20260722059000_control_tower_workers.sql"),"utf8");expect(worker).toContain("attempts>=8");expect(worker).toContain("dead_letter");expect(worker).toContain("power(2");});
});
