import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { recommendDispatch, type DispatchCandidate, type DispatchMission } from "@/lib/dispatch/engine";
import { ExternalMapProvider, haversineDistanceMeters, rankAddressSuggestions, structuredAddressSchema } from "@/lib/geolocation/provider";

const mission: DispatchMission = { id: "11111111-1111-4111-8111-111111111111", countryCode: "SN", city: "Dakar", zoneId: "DKR-1", point: { latitude: 14.7167, longitude: -17.4677 }, weightKg: 10, requiredVehicleTypes: ["van", "bike"], requiredSkills: ["delivery"], priority: "standard", slaMinutes: 120, sensitive: false, now: "2026-07-22T12:00:00.000Z", maxRadiusKm: 30 };
const candidate: DispatchCandidate = { id: "22222222-2222-4222-8222-222222222222", countryCode: "SN", city: "Dakar", zoneIds: ["DKR-1"], position: { latitude: 14.72, longitude: -17.46 }, positionRecordedAt: "2026-07-22T11:58:00.000Z", accuracyMeters: 20, online: true, available: true, vehicleType: "van", capacityKg: 100, currentLoadKg: 20, activeMissionCount: 1, skills: ["delivery"], serviceStartsAt: "08:00", serviceEndsAt: "18:00", performanceScore: 90, compliant: true };

describe("geolocation and dispatch foundation", () => {
  it("fails closed without a real mapping provider", async () => { await expect(new ExternalMapProvider("unconfigured").autocomplete({ query: "Keur Massar", limit: 6 })).rejects.toThrow("MAP_PROVIDER_ACCESS_REQUIRED"); });
  it("accepts informal addresses without street number or postal code", () => { expect(structuredAddressSchema.parse({ formattedAddress: "Près de la grande mosquée, Mbao, Sénégal", addressLine1: null, addressLine2: null, landmark: "Grande mosquée", neighborhood: "Mbao", commune: "Mbao", city: "Dakar", region: "Dakar", postalCode: null, country: "Sénégal", countryCode: "sn", latitude: 14.73, longitude: -17.32, providerPlaceId: "place-1", locationType: "landmark", geocodingProvider: "provider", accuracyLevel: "neighborhood", validationStatus: "selected" }).countryCode).toBe("SN"); });
  it("prioritizes country, city and proximity", () => { const base = structuredAddressSchema.parse({ formattedAddress: "Dakar, Sénégal", addressLine1: null, addressLine2: null, landmark: null, neighborhood: null, commune: null, city: "Dakar", region: null, postalCode: null, country: "Sénégal", countryCode: "SN", latitude: 14.7167, longitude: -17.4677, providerPlaceId: "dakar", locationType: "city", geocodingProvider: "provider", accuracyLevel: "city", validationStatus: "suggested" }); const foreign = { ...base, formattedAddress: "Paris, France", city: "Paris", country: "France", countryCode: "FR", providerPlaceId: "paris", latitude: 48.8566, longitude: 2.3522 }; expect(rankAddressSuggestions([foreign, base], { countryCode: "SN", city: "Dakar", proximity: mission.point })[0].providerPlaceId).toBe("dakar"); });
  it("uses geographic fallback visibly and requires approval", async () => { const result = await recommendDispatch({ mission, candidates: [candidate] }); expect(result[0]).toMatchObject({ candidateId: candidate.id, routeSource: "geographic_fallback", requiresHumanApproval: true }); expect(result[0].distanceMeters).toBeLessThan(2000); });
  it("uses provider road distance when available", async () => { const result = await recommendDispatch({ mission, candidates: [candidate], routeLookup: async () => ({ distanceMeters: 2500, durationSeconds: 600, trafficAware: true, provider: "provider", geometry: null }) }); expect(result[0]).toMatchObject({ distanceMeters: 2500, durationSeconds: 600, routeSource: "provider" }); });
  it("excludes offline, stale, inaccurate, saturated, non-compliant and wrong-zone agents", async () => { const variants = [{ ...candidate, online: false }, { ...candidate, positionRecordedAt: "2026-07-22T10:00:00.000Z" }, { ...candidate, accuracyMeters: 500 }, { ...candidate, currentLoadKg: 95 }, { ...candidate, compliant: false }, { ...candidate, zoneIds: ["OTHER"] }]; await expect(Promise.all(variants.map((item) => recommendDispatch({ mission, candidates: [item] })))).resolves.toEqual([[], [], [], [], [], []]); });
  it("returns no fabricated candidate when nobody is eligible", async () => { await expect(recommendDispatch({ mission, candidates: [] })).resolves.toEqual([]); });
  it("keeps debounce, cancellation, consent, retention and service-only purge explicit", () => { const component = readFileSync(resolve(process.cwd(), "components/forms/smart-address-field.tsx"), "utf8"); const sql = readFileSync(resolve(process.cwd(), "supabase/migrations/20260722053000_geolocation_dispatch_foundation.sql"), "utf8"); expect(component).toContain("AbortController"); expect(component).toContain("300"); expect(component).toContain("getCurrentPosition"); expect(sql).toContain("Active location consent required"); expect(sql).toContain("retention_until"); expect(sql).toContain("Self approval is forbidden"); expect(sql).toContain("to service_role"); });
  it("computes a stable geographic fallback", () => { expect(Math.round(haversineDistanceMeters({ latitude: 14.7167, longitude: -17.4677 }, { latitude: 14.7167, longitude: -17.4677 }))).toBe(0); });
});
