import { NextResponse,type NextRequest } from "next/server";
import { z } from "zod";
import { tryCreateSupabaseServerClient } from "@/lib/supabase/server";
import { getRelaySession } from "@relay-app/src/lib/auth";
import { assertRelayAccess } from "@relay-app/src/lib/permissions";
import { assertSameOrigin,rateLimit } from "@relay-app/src/lib/security";
import { correlationId,structuredLog } from "@relay-app/src/lib/observability";
const schema=z.object({trackingCode:z.string().trim().regex(/^YBL-[A-Z]{2}-\d{4}-\d{4}$/u),action:z.enum(["check_in","quality_checked","stored","check_out","handover","exception"]),relayPointId:z.string().uuid().optional(),idempotencyKey:z.string().min(8).max(160).regex(/^[a-zA-Z0-9:._-]+$/u),note:z.string().max(500).optional()});
export async function POST(request:NextRequest){const requestId=correlationId(request);try{assertSameOrigin(request);const limit=rateLimit(request,120,60_000);const session=await getRelaySession();if(!session)return NextResponse.json({error:"Authentification requise."},{status:401});assertRelayAccess(session.role,request.nextUrl.pathname,"POST");const payload=schema.parse(await request.json());if(session.source==="demo")return response({accepted:true,id:`demo-${payload.idempotencyKey}`,requestId,synchronized:false},limit.remaining);if(!payload.relayPointId)throw new Error("Point relais requis.");const supabase=await tryCreateSupabaseServerClient();if(!supabase)throw new Error("Supabase indisponible.");const scanType=payload.action==="check_in"?"check_in":payload.action==="check_out"?"check_out":payload.action==="handover"?"handover":"exception";const {data,error}=await supabase.rpc("record_relay_scan",{p_tracking_code:payload.trackingCode,p_relay_point_id:payload.relayPointId,p_scan_type:scanType,p_note:`${payload.action}:${payload.idempotencyKey}:${payload.note??""}`});if(error)throw new Error(error.message);structuredLog("info","relay_operation_recorded",{action:payload.action,requestId,role:session.role});return response({accepted:true,id:data,requestId,synchronized:true},limit.remaining)}catch(error){structuredLog("warn","relay_operation_rejected",{requestId,error:error instanceof Error?error.name:"UnknownError"});return NextResponse.json({error:error instanceof z.ZodError?"Opération invalide.":error instanceof Error?error.message:"Opération refusée.",requestId},{status:error instanceof z.ZodError?400:409})}}
function response(body:Record<string,unknown>,remaining:number){const result=NextResponse.json(body);result.headers.set("x-ratelimit-remaining",String(remaining));return result}
