import { ArrowRight, Box, MapPin, PackageCheck, ShieldCheck } from "lucide-react";
import { Button, Input, Select, Textarea, YobalelmaLogo, YbCard, YbEmptyState, YbLoader, YbMetric, YbNotice, YbPageHeader, YbSkeleton, YbStatus, YbTableFrame, YbTimeline } from "@yobalelma/ui";

export const metadata = { title: "Design System | Yobalelma" };

export default function DesignSystemPage() {
  return <main className="mx-auto max-w-[1440px] px-4 py-10 md:px-8 md:py-16">
    <div className="yb-brand-panel yb-modern-kente p-6 md:p-10"><YobalelmaLogo variant="light" className="h-auto w-52" /><div className="mt-16 max-w-3xl"><p className="yb-eyebrow">Design System officiel · 1.0</p><h1 className="yb-display mt-3">Le mouvement,<br /><span className="text-primary">mis en confiance.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/68">Une langue visuelle commune pour suivre, déplacer et orchestrer chaque envoi Yobalelma avec clarté.</p></div></div>

    <section className="mt-14"><YbPageHeader eyebrow="Fondations" title="Une signature, cinq métiers" description="L’orange de la marque guide l’action. Chaque produit reçoit un accent fonctionnel sans perdre l’identité Yobalelma." /><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[
      ["User", "Confiance", "bg-[#1688c5]"], ["Hub", "Précision", "bg-[#1b99a7]"], ["Relay", "Proximité", "bg-[#208c5a]"], ["Collection", "Mobilité", "bg-[#7650cf]"], ["Admin", "Commandement", "bg-primary"],
    ].map(([name, quality, color]) => <YbCard className="p-4" key={name}><span className={`block h-20 rounded-xl ${color}`} /><p className="mt-4 font-extrabold">{name}</p><p className="text-sm text-muted-foreground">{quality}</p></YbCard>)}</div></section>

    <section className="mt-14"><YbPageHeader eyebrow="Pilotage" title="Indicateurs lisibles en un regard" /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><YbMetric label="Expéditions actives" value="12 480" detail="+8,4 % cette semaine" icon={Box} /><YbMetric label="Livrées dans les délais" value="97,2 %" detail="Objectif international atteint" icon={PackageCheck} /><YbMetric label="Points connectés" value="284" detail="Dans 16 régions" icon={MapPin} /><YbMetric label="Alertes prioritaires" value="06" detail="Toutes prises en charge" icon={ShieldCheck} /></div></section>

    <section className="mt-14 grid gap-6 lg:grid-cols-2"><YbCard className="p-6"><h2 className="text-xl font-extrabold">Actions et formulaires</h2><div className="mt-6 flex flex-wrap gap-3"><Button>Créer un envoi <ArrowRight className="h-4 w-4" /></Button><Button variant="secondary">Action secondaire</Button><Button variant="ghost">Action discrète</Button></div><div className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-bold">Référence de suivi<Input placeholder="Ex. YBL-2026-0482" /></label><label className="grid gap-2 text-sm font-bold">Type d’opération<Select defaultValue="delivery"><option value="delivery">Livraison</option><option value="collection">Collecte</option></Select></label><label className="grid gap-2 text-sm font-bold">Instructions<Textarea placeholder="Précisez les informations utiles…" /></label></div></YbCard><YbCard className="p-6"><h2 className="text-xl font-extrabold">États d’expédition</h2><div className="mt-5 flex flex-wrap gap-2"><YbStatus tone="info">En préparation</YbStatus><YbStatus tone="warning">En transit</YbStatus><YbStatus tone="success">Livré</YbStatus><YbStatus tone="danger">Action requise</YbStatus></div><YbTimeline className="mt-8" items={[{ id: "1", title: "Colis confié", description: "Enregistrement sécurisé au point de départ", state: "complete", meta: "08:42" }, { id: "2", title: "En route vers le Hub", description: "Transport suivi en temps réel", state: "complete", meta: "10:16" }, { id: "3", title: "Contrôle Hub", description: "Vérification et préparation du prochain segment", state: "current", meta: "Maintenant" }, { id: "4", title: "Remise au destinataire", state: "upcoming" }]} /></YbCard></section>

    <section className="mt-14"><YbPageHeader eyebrow="Données" title="Tableaux conçus pour décider" /><YbTableFrame className="mt-7" label="Exemple des expéditions"><table><thead><tr><th>Référence</th><th>Parcours</th><th>Responsable</th><th>Statut</th></tr></thead><tbody><tr><td className="font-extrabold">YBL-0482</td><td>Dakar → Paris</td><td>Aminata Diallo</td><td><YbStatus tone="success">Conforme</YbStatus></td></tr><tr><td className="font-extrabold">YBL-0483</td><td>Thiès → Lyon</td><td>Moussa Fall</td><td><YbStatus tone="warning">En transit</YbStatus></td></tr></tbody></table></YbTableFrame></section>

    <section className="mt-14 grid gap-6 lg:grid-cols-2"><YbNotice title="Traçabilité confirmée" tone="success">Les preuves de remise sont disponibles et l’historique est complet.</YbNotice><YbEmptyState title="Tout est sous contrôle" description="Aucune action prioritaire n’est requise pour cette zone." action={<Button variant="secondary">Voir l’activité</Button>} /></section>
    <section className="mt-14"><YbPageHeader eyebrow="Chargement" title="Retour visuel calme et explicite" /><div className="mt-6 grid gap-6 rounded-2xl border bg-card p-6 sm:grid-cols-2"><YbLoader label="Synchronisation des opérations" /><div className="grid gap-3"><YbSkeleton className="w-1/3" /><YbSkeleton className="w-full" /><YbSkeleton className="w-4/5" /></div></div></section>
    <footer className="mt-20 flex flex-col gap-4 border-t pt-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><YobalelmaLogo className="h-auto w-36" /><p>Design System Yobalelma · Conçu pour relier chaque mouvement.</p></footer>
  </main>;
}
