import type {TowerKpis} from "./core";
export type TowerRecommendation={type:string;priority:"medium"|"high"|"critical";title:string;explanation:string;evidence:Array<{metric:string;value:number}>;alternatives:string[];confidence:number;requiresHumanApproval:true};
export function generateOperationalRecommendations(kpis:TowerKpis):TowerRecommendation[]{
  const result:TowerRecommendation[]=[];
  if(kpis.hubCapacityPercent>=85) result.push({type:"change_hub",priority:kpis.hubCapacityPercent>=95?"critical":"high",title:"Rééquilibrer la capacité Hub",explanation:`La capacité agrégée atteint ${kpis.hubCapacityPercent} %. Vérifier les hubs voisins avant tout reroutage.`,evidence:[{metric:"hub_capacity_percent",value:kpis.hubCapacityPercent}],alternatives:["Décaler une collecte","Ouvrir une capacité temporaire","Utiliser un hub voisin autorisé"],confidence:85,requiresHumanApproval:true});
  if(kpis.staleDrivers>0) result.push({type:"verify_driver_signal",priority:"high",title:"Contrôler les signaux terrain",explanation:`${kpis.staleDrivers} chauffeur(s) en mission n'ont pas de position fraîche. Contacter les équipes avant une réaffectation.`,evidence:[{metric:"stale_drivers",value:kpis.staleDrivers}],alternatives:["Attendre la reprise réseau","Contacter le conducteur","Préparer une réaffectation"],confidence:80,requiresHumanApproval:true});
  if(kpis.customsBlocked>0) result.push({type:"customs_escalation",priority:"high",title:"Traiter les blocages douaniers",explanation:`${kpis.customsBlocked} expédition(s) nécessitent une décision ou une pièce officielle.`,evidence:[{metric:"customs_blocked",value:kpis.customsBlocked}],alternatives:["Demander les pièces","Escalader au responsable douane","Suspendre le départ concerné"],confidence:90,requiresHumanApproval:true});
  if(kpis.paymentExceptions>0) result.push({type:"payment_review",priority:"high",title:"Revoir les exceptions financières",explanation:`${kpis.paymentExceptions} transaction(s) sont en échec ou en attente anormale. Aucun statut client ne doit être forcé.`,evidence:[{metric:"payment_exceptions",value:kpis.paymentExceptions}],alternatives:["Relancer le rapprochement","Attendre le webhook","Ouvrir un incident fournisseur"],confidence:90,requiresHumanApproval:true});
  return result;
}
