"use client";
import { LocateFixed, MapPin, Search, ShieldCheck } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";
import type { StructuredAddress } from "@/lib/geolocation/provider";

export function SmartAddressField({ countryCode, label, onSelect, onTextChange, value }: { countryCode?: string; label: string; onSelect(address: StructuredAddress): void; onTextChange(value: string): void; value: string }) {
  const id = useId(); const abortRef = useRef<AbortController | null>(null); const [suggestions, setSuggestions] = useState<StructuredAddress[]>([]); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [selected, setSelected] = useState(false);
  useEffect(() => { if (selected || value.trim().length < 2) { setSuggestions([]); return; } const timer = window.setTimeout(async () => { abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setPending(true); setMessage(""); try { const response = await fetch("/api/locations/autocomplete", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query: value, countryCode: countryCode?.length === 2 ? countryCode.toUpperCase() : undefined, limit: 6 }), signal: controller.signal }); const body = await response.json() as { suggestions?: StructuredAddress[]; error?: string }; if (!response.ok) throw new Error(body.error || "Recherche indisponible."); setSuggestions(body.suggestions ?? []); } catch (error) { if ((error as Error).name !== "AbortError") setMessage(error instanceof Error ? error.message : "Recherche indisponible."); } finally { if (!controller.signal.aborted) setPending(false); } }, 300); return () => window.clearTimeout(timer); }, [countryCode, selected, value]);
  const usePosition = () => { if (!navigator.geolocation) { setMessage("Ce navigateur ne permet pas la localisation."); return; } setPending(true); setMessage(""); navigator.geolocation.getCurrentPosition(async (position) => { try { if (position.coords.accuracy > 1000) setMessage("La position est imprécise. Vérifiez le point proposé."); const response = await fetch("/api/locations/reverse", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude }) }); const body = await response.json() as { address?: StructuredAddress; error?: string }; if (!response.ok || !body.address) throw new Error(body.error || "Position non reconnue."); choose({ ...body.address, accuracyLevel: position.coords.accuracy <= 30 ? "rooftop" : position.coords.accuracy <= 200 ? "street" : "approximate" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Position non reconnue."); } finally { setPending(false); } }, (error) => { setPending(false); setMessage(error.code === error.PERMISSION_DENIED ? "Autorisation refusée. Vous pouvez rechercher l’adresse manuellement." : "La position actuelle n’est pas disponible."); }, { enableHighAccuracy: true, maximumAge: 30_000, timeout: 12_000 }); };
  const choose = (address: StructuredAddress) => { setSelected(true); setSuggestions([]); onTextChange(address.formattedAddress); onSelect({ ...address, validationStatus: "selected" }); };
  return <div className="grid gap-2"><label className="text-sm font-semibold" htmlFor={id}>{label}</label><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><input id={id} className="yb-field pl-10 pr-10" autoComplete="off" value={value} role="combobox" aria-autocomplete="list" aria-expanded={suggestions.length > 0} aria-controls={`${id}-list`} onChange={(event) => { setSelected(false); onTextChange(event.target.value); }} /><span className="absolute right-3 top-3.5">{pending ? <span className="block h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" /> : selected ? <ShieldCheck className="h-4 w-4 text-success" /> : <MapPin className="h-4 w-4 text-muted-foreground" />}</span></div>{suggestions.length ? <ul id={`${id}-list`} className="max-h-80 overflow-y-auto rounded-xl border bg-background p-1 shadow-xl" role="listbox">{suggestions.map((item) => <li key={`${item.geocodingProvider}:${item.providerPlaceId}`}><button className="flex w-full items-start gap-3 rounded-lg p-3 text-left hover:bg-muted focus:bg-muted" type="button" onClick={() => choose(item)}><MapPin className="mt-1 h-4 w-4 shrink-0 text-primary" /><span><span className="block font-black">{item.formattedAddress}</span><span className="mt-1 block text-xs text-muted-foreground">{item.locationType} · {item.city} · {item.country}{item.distanceMeters ? ` · ${(item.distanceMeters / 1000).toFixed(1)} km` : ""}</span></span></button></li>)}</ul> : null}<button className="inline-flex min-h-11 items-center gap-2 justify-self-start rounded-lg border px-3 text-sm font-black hover:border-primary" type="button" onClick={usePosition}><LocateFixed className="h-4 w-4" />Utiliser ma position actuelle</button>{message ? <p className="text-sm font-semibold text-amber-800" role="status">{message}</p> : null}</div>;
}
